"use client";
import Link from "next/link";
import { useState } from "react";
import WebsiteSeoCard from "@/components/website-seo/ui/WebsiteSeoCard";
import type { Cluster } from "@/lib/website-seo/search-intelligence/types";
import { buttonClass, contentClass, FactoryLink, Feedback, inputClass, SearchHeading, tableClass, useSearchData } from "./shared";
export default function ClustersClient() {
  const { data, loading, error, reload } = useSearchData<Cluster[]>("search-intelligence/clusters");
  const [search, setSearch] = useState(""); const [mapping, setMapping] = useState(""); const [offset, setOffset] = useState(0);
  const rows = (data ?? []).filter((row) => (!search || `${row.clusterKey} ${row.primaryKeywords.map((k) => k.keyword).join(" ")}`.toLowerCase().includes(search.toLowerCase())) && (!mapping || row.mapped === (mapping === "mapped")));
  return <><SearchHeading title="W4 Cluster Intelligence" action={<button disabled={loading} className={buttonClass} onClick={reload}>Reload</button>} /><div className={contentClass}><Feedback loading={loading} error={error} /><WebsiteSeoCard><p className="text-sm text-zinc-500">Clusters and primary relationships are derived from W4. Keywords without a cluster key are not assigned an invented cluster.</p><div className="my-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Search<input value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} className={inputClass} /></label><label className="text-sm font-bold">Entity mapping<select value={mapping} onChange={(e) => { setMapping(e.target.value); setOffset(0); }} className={inputClass}><option value="">All</option><option value="mapped">All keywords mapped</option><option value="unmapped">Has unmapped keywords</option></select></label></div>
    {!loading && !error && <><div className="overflow-auto"><table className={tableClass}><thead><tr>{["Cluster", "Primary keyword", "Keywords", "Intents / types", "Statuses", "Entity mapping"].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.slice(offset, offset + 25).map((row) => <tr key={row.clusterKey}><td className="max-w-52 break-all"><Link className="font-bold text-red-600" href={`/website-seo/search-intelligence/keywords?cluster=${encodeURIComponent(row.clusterKey)}`}>{row.clusterKey}</Link></td><td>{row.primaryKeywords.map((k) => k.keyword).join(", ") || "Unavailable"}</td><td>{row.keywordCount}</td><td>{row.intents.join(", ")}<p className="mt-1 text-xs text-zinc-500">{row.types.join(", ")}</p></td><td>{row.statuses.join(", ")}</td><td>{row.entities.map((entity) => <p key={entity.id}><FactoryLink {...entity} /></p>)}<p className="text-xs">{row.mapped ? "Mapped" : `${row.unmappedKeywords} unmapped`}</p></td></tr>)}</tbody></table></div>{!rows.length && <p className="py-8 text-center text-sm text-zinc-500">No clusters match these filters.</p>}<div className="mt-4 flex gap-3"><button className={buttonClass} disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 25))}>Previous</button><button className={buttonClass} disabled={offset + 25 >= rows.length} onClick={() => setOffset(offset + 25)}>Next</button></div></>}
  </WebsiteSeoCard></div></>;
}
