"use client";
import { useRef, useState } from "react";
import WebsiteSeoCard from "@/components/website-seo/ui/WebsiteSeoCard";
import { COMPETITOR_STATUSES, type CompetitorInput } from "@/lib/website-seo/search-intelligence/types";
import { buttonClass, contentClass, Feedback, inputClass, primaryClass, searchApi, SearchHeading, tableClass, useMutation, useSearchData } from "./shared";
export interface CompetitorRow extends CompetitorInput { id: string; createdAt: string; updatedAt: string }
export default function CompetitorsClient() {
  const { data, loading, error, reload } = useSearchData<CompetitorRow[]>("search-intelligence/competitors");
  const [selected, setSelected] = useState<CompetitorRow | null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [offset, setOffset] = useState(0);
  const mutation = useMutation(); const form = useRef<HTMLFormElement>(null);
  const rows = (data ?? []).filter((row) => (!search || `${row.name} ${row.domain}`.toLowerCase().includes(search.toLowerCase())) && (!status || row.status === status));
  return <><SearchHeading title="Competitor Manager" action={<button className={buttonClass} disabled={loading || mutation.busy} onClick={reload}>Reload</button>} /><div className={contentClass}><Feedback error={mutation.error || error} notice={mutation.notice} loading={loading} />
    <WebsiteSeoCard><h2 className="text-lg font-black">{selected ? "Edit competitor" : "Add competitor"}</h2><p className="mt-2 text-sm text-zinc-500">Domains are normalized for uniqueness. Saving a competitor does not crawl its website.</p>
      <form key={selected?.id || "new"} ref={form} className="mt-4" onSubmit={(event) => { event.preventDefault(); const fields = new FormData(event.currentTarget); void mutation.run(async () => {
        await searchApi(`search-intelligence/competitors${selected ? `/${encodeURIComponent(selected.id)}` : ""}`, selected ? "PATCH" : "POST", { name: fields.get("name"), domain: fields.get("domain"), status: fields.get("status"), notes: fields.get("notes") });
        form.current?.reset(); setSelected(null); mutation.setNotice("Competitor saved."); reload();
      }); }}><fieldset disabled={mutation.busy || loading || !data} className="grid items-end gap-4 sm:grid-cols-2 disabled:opacity-60"><label className="text-sm font-bold">Name<input name="name" required maxLength={200} defaultValue={selected?.name || ""} className={inputClass} /></label><label className="text-sm font-bold">Domain<input name="domain" required maxLength={2048} defaultValue={selected?.domain || ""} className={inputClass} /></label><label className="text-sm font-bold">Status<select name="status" defaultValue={selected?.status || "ACTIVE"} className={inputClass}>{COMPETITOR_STATUSES.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-bold">Notes<textarea name="notes" maxLength={4000} defaultValue={selected?.notes || ""} className={inputClass} /></label><div className="flex gap-3"><button className={primaryClass} type="submit">{mutation.busy ? "Saving…" : "Save competitor"}</button>{selected && <button type="button" className={buttonClass} onClick={() => setSelected(null)}>Cancel edit</button>}</div></fieldset></form>
    </WebsiteSeoCard><WebsiteSeoCard><div className="mb-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Search<input value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} className={inputClass} /></label><label className="text-sm font-bold">Status<select value={status} onChange={(e) => { setStatus(e.target.value); setOffset(0); }} className={inputClass}><option value="">All statuses</option>{COMPETITOR_STATUSES.map((value) => <option key={value}>{value}</option>)}</select></label></div>
      {!loading && !error && <><div className="overflow-auto"><table className={tableClass}><thead><tr><th>Name</th><th>Domain</th><th>Status</th><th>Notes</th><th>Actions</th></tr></thead><tbody>{rows.slice(offset, offset + 25).map((row) => <tr key={row.id}><td className="font-bold">{row.name}</td><td>{row.domain}</td><td>{row.status}</td><td className="max-w-xs whitespace-pre-wrap break-words">{row.notes || "—"}</td><td><div className="flex gap-2"><button disabled={mutation.busy} className={buttonClass} onClick={() => setSelected(row)}>Edit</button><button disabled={mutation.busy || row.status === "ARCHIVED"} className={buttonClass} onClick={() => void mutation.run(async () => { await searchApi(`search-intelligence/competitors/${encodeURIComponent(row.id)}`, "DELETE"); if (selected?.id === row.id) setSelected(null); mutation.setNotice("Competitor archived. Observation history retained."); reload(); })}>Archive</button></div></td></tr>)}</tbody></table></div>{!rows.length && <p className="py-8 text-center text-sm text-zinc-500">No competitors match these filters.</p>}<div className="mt-4 flex gap-3"><button className={buttonClass} disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 25))}>Previous</button><button className={buttonClass} disabled={offset + 25 >= rows.length} onClick={() => setOffset(offset + 25)}>Next</button></div></>}
    </WebsiteSeoCard>
  </div></>;
}
