"use client";
import { useEffect, useMemo, useState } from "react";
import WebsiteSeoCard from "@/components/website-seo/ui/WebsiteSeoCard";
import { WEBSITE_KEYWORD_TYPES, WEBSITE_KEYWORD_INTENTS, WEBSITE_KEYWORD_STATUSES } from "@/lib/website-seo/keywords/types";
import { WEBSITE_ENTITY_TYPES } from "@/lib/website-seo/entities/types";
import { deriveOpportunities } from "@/lib/website-seo/search-intelligence/engine";
import type { EntitySource, KeywordSource, Opportunity, PageSource, RealMetrics } from "@/lib/website-seo/search-intelligence/types";
import { buttonClass, contentClass, FactoryLink, Feedback, inputClass, metric, SearchHeading, tableClass, useSearchData } from "./shared";
export default function KeywordViewsClient({ opportunities = false }: { opportunities?: boolean }) {
  const rows = useSearchData<Opportunity[] | KeywordSource[]>(opportunities ? "search-intelligence/opportunities" : "keywords");
  const entities = useSearchData<EntitySource[]>("entities"); const pages = useSearchData<PageSource[]>("pages");
  const [search, setSearch] = useState(""); const [type, setType] = useState(""); const [intent, setIntent] = useState(""); const [status, setStatus] = useState(""); const [entityType, setEntityType] = useState(""); const [cluster, setCluster] = useState(""); const [mapping, setMapping] = useState("");
  const [sort, setSort] = useState<keyof RealMetrics>("opportunityScore"); const [direction, setDirection] = useState("desc"); const [minimum, setMinimum] = useState(""); const [offset, setOffset] = useState(0);
  useEffect(() => { setCluster(new URLSearchParams(window.location.search).get("cluster") || ""); }, []);
  const source = useMemo(() => rows.data && entities.data && pages.data ? opportunities ? rows.data as Opportunity[] : deriveOpportunities(rows.data, entities.data, pages.data) : [], [rows.data, entities.data, pages.data, opportunities]);
  const filtered = source.filter((row) => (!search || row.keyword.toLowerCase().includes(search.toLowerCase())) && (!type || row.type === type) && (!intent || row.intent === intent) && (!status || row.status === status) && (!entityType || row.entityType === entityType) && (!cluster || row.clusterKey === cluster) && (!mapping || (mapping === "mapped" ? row.mapped : mapping === "unmapped" ? !row.mapped : !row.pages.length)) && (!minimum || (row.metrics[sort] !== null && row.metrics[sort]! >= Number(minimum))))
    .sort((a, b) => { const av = a.metrics[sort], bv = b.metrics[sort]; if (av === null) return bv === null ? a.keyword.localeCompare(b.keyword) : 1; if (bv === null) return -1; return (direction === "asc" ? av - bv : bv - av) || a.keyword.localeCompare(b.keyword); });
  useEffect(() => setOffset(0), [search, type, intent, status, entityType, cluster, mapping, sort, minimum, direction]);
  const loading = rows.loading || entities.loading || pages.loading; const error = rows.error || entities.error || pages.error;
  const selects = [{ label: "Type", value: type, setter: setType, options: WEBSITE_KEYWORD_TYPES }, { label: "Intent", value: intent, setter: setIntent, options: WEBSITE_KEYWORD_INTENTS }, { label: "Status", value: status, setter: setStatus, options: WEBSITE_KEYWORD_STATUSES }, { label: "Entity type", value: entityType, setter: setEntityType, options: WEBSITE_ENTITY_TYPES }];
  return <><SearchHeading title={opportunities ? "Keyword Opportunities" : "W4 Keywords"} action={<button disabled={loading} onClick={() => { rows.reload(); entities.reload(); pages.reload(); }} className={buttonClass}>Reload</button>} /><div className={contentClass}><Feedback loading={loading} error={error} /><WebsiteSeoCard>
    <p className="text-sm text-zinc-500">Metrics come from W4. Missing metrics remain unavailable; a stored opportunity score is not a measured rank or traffic estimate.</p>
    <div className="my-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold">Search<input value={search} onChange={(e) => setSearch(e.target.value)} className={inputClass} /></label>{selects.map((filter) => <label key={filter.label} className="text-xs font-bold">{filter.label}<select value={filter.value} onChange={(e) => filter.setter(e.target.value)} className={inputClass}><option value="">All</option>{filter.options.map((value) => <option key={value}>{value}</option>)}</select></label>)}
      <label className="text-xs font-bold">Cluster<select value={cluster} onChange={(e) => setCluster(e.target.value)} className={inputClass}><option value="">All clusters</option>{[...new Set(source.map((row) => row.clusterKey).filter((key): key is string => Boolean(key)))].map((key) => <option key={key}>{key}</option>)}</select></label>
      <label className="text-xs font-bold">Mapping<select value={mapping} onChange={(e) => setMapping(e.target.value)} className={inputClass}><option value="">All</option><option value="mapped">Entity mapped</option><option value="unmapped">Entity unmapped</option><option value="no-page">No generated page</option></select></label>
      <label className="text-xs font-bold">Metric / sort<select value={sort} onChange={(e) => setSort(e.target.value as keyof RealMetrics)} className={inputClass}>{["opportunityScore", "searchVolume", "difficulty", "cpc", "competition"].map((key) => <option key={key}>{key}</option>)}</select></label>
      <label className="text-xs font-bold">Order<select value={direction} onChange={(e) => setDirection(e.target.value)} className={inputClass}><option value="desc">Highest first</option><option value="asc">Lowest first</option></select></label>
      <label className="text-xs font-bold">Minimum selected metric<input type="number" min="0" value={minimum} onChange={(e) => setMinimum(e.target.value)} className={inputClass} /></label>
    </div>
    {!loading && !error && <><p className="mb-3 text-xs text-zinc-500">{filtered.length} keywords</p><div className="overflow-auto"><table className={tableClass}><thead><tr>{["Keyword", "Classification", "Cluster", "Entity / pages", "Score", "Volume", "Difficulty", "CPC", "Competition"].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{filtered.slice(offset, offset + 25).map((row) => <tr key={row.id}><td className="font-bold">{row.keyword}</td><td>{row.type}<br />{row.intent}<br />{row.status}</td><td className="max-w-48 break-all">{row.clusterKey || "Unclustered"}</td><td>{row.entity ? <FactoryLink {...row.entity} /> : "Unmapped"}{row.pages.map((page) => <p key={page.id} className="mt-1 text-xs">{page.pathname} · {page.status}</p>)}</td>{(["opportunityScore", "searchVolume", "difficulty", "cpc", "competition"] as const).map((key) => <td key={key}>{metric(row.metrics[key])}</td>)}</tr>)}</tbody></table></div>{!filtered.length && <p className="py-8 text-center text-sm text-zinc-500">No W4 keywords match these filters.</p>}<div className="mt-4 flex gap-3"><button className={buttonClass} disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 25))}>Previous</button><button className={buttonClass} disabled={offset + 25 >= filtered.length} onClick={() => setOffset(offset + 25)}>Next</button></div></>}
  </WebsiteSeoCard></div></>;
}
