"use client";
import { useRef, useState } from "react";
import WebsiteSeoCard from "@/components/website-seo/ui/WebsiteSeoCard";
import type { ObservationKind, ObservationSubject } from "@/lib/website-seo/search-intelligence/types";
import type { CompetitorRow } from "./CompetitorsClient";
import { buttonClass, contentClass, Feedback, inputClass, metric, primaryClass, ProviderNotice, searchApi, SearchHeading, tableClass, useMutation, useSearchData } from "./shared";
interface ObservationRow { id: string; kind: string; subject: string; query: string; provider: string; competitor: CompetitorRow | null; rank: number | null; visibilityScore: number | null; mentioned: boolean | null; cited: boolean | null; url: string | null; observedAt: string; keywordId: string | null; pageId: string | null; metadata: { sourceType?: string; notes?: string; evidenceUrl?: string } | null }
interface ObservationList { items: ObservationRow[]; total: number; offset: number; limit: number }
interface KeywordRef { id: string; keyword: string; entityId: string | null }
interface PageRef { id: string; pathname: string; entityId: string }
const yesNo = (value: boolean | null) => value === null ? "Unknown" : value ? "Yes" : "No";
export default function ObservationsClient({ kind }: { kind: ObservationKind }) {
  const organic = kind === "ORGANIC_RANKING";
  const [search, setSearch] = useState(""); const [subjectFilter, setSubjectFilter] = useState(""); const [competitorFilter, setCompetitorFilter] = useState(""); const [offset, setOffset] = useState(0);
  const [subject, setSubject] = useState<ObservationSubject>("OWN_SITE");
  const params = new URLSearchParams({ kind, search, subject: subjectFilter, competitorId: competitorFilter, offset: String(offset), limit: "50" });
  const { data, loading, error, reload } = useSearchData<ObservationList>(`search-intelligence/observations?${params}`);
  const competitors = useSearchData<CompetitorRow[]>("search-intelligence/competitors"); const keywords = useSearchData<KeywordRef[]>("keywords"); const pages = useSearchData<PageRef[]>("pages");
  const mutation = useMutation(); const form = useRef<HTMLFormElement>(null);
  return <><SearchHeading title={organic ? "Organic Ranking Observations" : "AI Visibility Observations"} action={<button disabled={loading || mutation.busy} className={buttonClass} onClick={() => { reload(); competitors.reload(); keywords.reload(); pages.reload(); }}>Reload</button>} /><div className={contentClass}><Feedback error={mutation.error || error || competitors.error || keywords.error || pages.error} notice={mutation.notice} loading={loading} /><ProviderNotice />
    <WebsiteSeoCard><h2 className="text-lg font-black">Record a manual observation</h2><p className="mt-2 text-sm text-zinc-500">Enter a result you observed and name the source/provider. Leave unavailable values blank. These entries are admin-reported, not independently verified by RideGrid.</p>
      <form ref={form} className="mt-4" onSubmit={(event) => { event.preventDefault(); const fields = new FormData(event.currentTarget); void mutation.run(async () => {
        const nullable = (key: string) => String(fields.get(key) || "").trim() || null;
        const numeric = (key: string) => nullable(key) === null ? null : Number(fields.get(key));
        const boolean = (key: string) => nullable(key) === null ? null : fields.get(key) === "true";
        const observedAt = new Date(String(fields.get("observedAt")));
        if (!Number.isFinite(observedAt.getTime())) throw new Error("Supply a valid observed time.");
        await searchApi("search-intelligence/observations", "POST", { kind, subject, provider: fields.get("provider"), query: fields.get("query"), competitorId: subject === "COMPETITOR" ? nullable("competitorId") : null,
          keywordId: nullable("keywordId"), pageId: nullable("pageId"), url: nullable("url"), observedAt: observedAt.toISOString(),
          ...(organic ? { rank: numeric("rank") } : { visibilityScore: numeric("visibilityScore"), mentioned: boolean("mentioned"), cited: boolean("cited") }),
          metadata: { sourceType: "MANUAL", ...(nullable("notes") ? { notes: nullable("notes") } : {}), ...(nullable("evidenceUrl") ? { evidenceUrl: nullable("evidenceUrl") } : {}) },
        });
        form.current?.reset(); setSubject("OWN_SITE"); mutation.setNotice("Manual observation recorded with its supplied source. No independent verification performed."); setOffset(0); reload();
      }); }}><fieldset disabled={mutation.busy || loading || !data} className="grid items-end gap-4 md:grid-cols-2 lg:grid-cols-3 disabled:opacity-60">
        <label className="text-sm font-bold">Query<input name="query" required maxLength={500} className={inputClass} /></label><label className="text-sm font-bold">Source / provider<input name="provider" required maxLength={120} className={inputClass} /></label>
        <label className="text-sm font-bold">Subject<select value={subject} onChange={(e) => setSubject(e.target.value as ObservationSubject)} className={inputClass}><option>OWN_SITE</option><option>COMPETITOR</option></select></label>
        {subject === "COMPETITOR" && <label className="text-sm font-bold">Competitor<select name="competitorId" required className={inputClass}><option value="">Select competitor</option>{competitors.data?.map((row) => <option key={row.id} value={row.id}>{row.name} · {row.status}</option>)}</select></label>}
        <label className="text-sm font-bold">Observed time (your local time)<input type="datetime-local" step="1" name="observedAt" required className={inputClass} /></label>
        {organic ? <label className="text-sm font-bold">Rank (optional)<input name="rank" type="number" min="1" step="1" max="2147483647" className={inputClass} /></label> : <><label className="text-sm font-bold">Visibility score (optional)<input name="visibilityScore" type="number" min="0" max="100" step="any" className={inputClass} /></label>{["mentioned", "cited"].map((key) => <label key={key} className="text-sm font-bold capitalize">{key}<select name={key} defaultValue="" className={inputClass}><option value="">Unknown</option><option value="true">Yes</option><option value="false">No</option></select></label>)}</>}
        <label className="text-sm font-bold">Result URL (optional)<input type="url" name="url" maxLength={2048} className={inputClass} /></label>
        <label className="text-sm font-bold">W4 keyword (optional)<select name="keywordId" defaultValue="" className={inputClass}><option value="">No keyword relation</option>{keywords.data?.map((row) => <option key={row.id} value={row.id}>{row.keyword}</option>)}</select></label>
        <label className="text-sm font-bold">W3 page (optional)<select name="pageId" defaultValue="" className={inputClass}><option value="">No page relation</option>{pages.data?.map((row) => <option key={row.id} value={row.id}>{row.pathname}</option>)}</select></label>
        <label className="text-sm font-bold">Evidence URL (optional)<input type="url" name="evidenceUrl" maxLength={2048} className={inputClass} /></label>
        <label className="text-sm font-bold">Evidence notes (optional)<input name="notes" maxLength={2000} className={inputClass} /></label>
        <button type="submit" className={primaryClass}>{mutation.busy ? "Recording…" : "Record manual observation"}</button>
      </fieldset></form>
    </WebsiteSeoCard><WebsiteSeoCard><h2 className="text-lg font-black">Observation history · latest first</h2><div className="my-4 grid gap-3 md:grid-cols-3"><label className="text-sm font-bold">Query search<input value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} className={inputClass} /></label><label className="text-sm font-bold">Subject<select value={subjectFilter} onChange={(e) => { setSubjectFilter(e.target.value); setOffset(0); }} className={inputClass}><option value="">All subjects</option><option>OWN_SITE</option><option>COMPETITOR</option></select></label><label className="text-sm font-bold">Competitor<select value={competitorFilter} onChange={(e) => { setCompetitorFilter(e.target.value); setOffset(0); }} className={inputClass}><option value="">All competitors</option>{competitors.data?.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label></div>
      {data && <><p className="mb-3 text-xs text-zinc-500">{data.total} stored observations · newest matching observation: {data.items[0] ? new Date(data.items[0].observedAt).toLocaleString() : "None"}</p><div className="overflow-auto"><table className={tableClass}><thead><tr><th>Query / subject</th><th>{organic ? "Rank" : "Visibility / mentioned / cited"}</th><th>Source / provider</th><th>URL</th><th>Observed</th><th>Relations / evidence</th></tr></thead><tbody>{data.items.map((row) => <tr key={row.id}><td><p className="font-bold">{row.query}</p><p className="text-xs">{row.subject}{row.competitor ? ` · ${row.competitor.name}` : ""}</p></td><td>{organic ? metric(row.rank) : <>{metric(row.visibilityScore)}<p className="text-xs">Mentioned: {yesNo(row.mentioned)}<br />Cited: {yesNo(row.cited)}</p></>}</td><td>{row.provider}<p className="text-xs text-zinc-500">{row.metadata?.sourceType || "Source unspecified"} · supplied</p></td><td className="max-w-60 break-all">{row.url ? <a href={row.url} target="_blank" rel="noopener noreferrer" className="text-red-600">{row.url}</a> : "Unavailable"}</td><td>{new Date(row.observedAt).toLocaleString()}</td><td className="max-w-xs break-words text-xs">{row.keywordId && <p>Keyword: {keywords.data?.find((keyword) => keyword.id === row.keywordId)?.keyword || row.keywordId}</p>}{row.pageId && <p>Page: {pages.data?.find((page) => page.id === row.pageId)?.pathname || row.pageId}</p>}{row.metadata?.notes && <p>{row.metadata.notes}</p>}{row.metadata?.evidenceUrl && <a href={row.metadata.evidenceUrl} target="_blank" rel="noopener noreferrer" className="text-red-600">Evidence URL</a>}</td></tr>)}</tbody></table></div>{!data.items.length && <p className="py-8 text-center text-sm text-zinc-500">No {organic ? "ranking" : "AI visibility"} observations recorded for these filters.</p>}<div className="mt-4 flex gap-3"><button disabled={loading || offset === 0} className={buttonClass} onClick={() => setOffset(Math.max(0, offset - 50))}>Previous</button><button disabled={loading || offset + 50 >= data.total} className={buttonClass} onClick={() => setOffset(offset + 50)}>Next</button></div></>}
    </WebsiteSeoCard>
  </div></>;
}
