'use client';

import { recentReports } from '@/data/reports';

const statusColors: Record<string, string> = {
  Completed: 'bg-green-100 text-green-700',
  Processing: 'bg-amber-100 text-amber-700',
  Scheduled: 'bg-blue-100 text-blue-700',
};

export default function RecentReports() {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="flex items-center justify-between border-b border-slate-200 px-6 py-5">
        <div>
          <h2 className="text-xl font-bold text-slate-900">Recent Reports</h2>

          <p className="mt-1 text-sm text-slate-500">
            Recently generated reports across the platform
          </p>
        </div>

        <button className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium hover:bg-slate-100">
          View All
        </button>
      </div>

      <div className="divide-y divide-slate-100">
        {recentReports.map((report) => (
          <div
            key={report.id}
            className="flex flex-col gap-4 p-6 transition hover:bg-slate-50 lg:flex-row lg:items-center lg:justify-between"
          >
            <div>
              <h3 className="font-semibold text-slate-900">{report.report}</h3>

              <p className="mt-1 text-sm text-slate-500">
                ID: {report.id} • Generated by {report.generatedBy}
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-3">
              <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600">
                {report.format}
              </span>

              <span className="text-sm text-slate-500">{report.date}</span>

              <span
                className={`rounded-full px-3 py-1 text-xs font-semibold ${
                  statusColors[report.status]
                }`}
              >
                {report.status}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
