"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { FareDetails, FareDetailsValue } from "./FareDetails";
import LegacyPackages from "./LegacyPackages";

type Row = Record<string, any>;
const tabs=["Pricing Overview","Vendor Rate Cards","Route Pricing","Approval Queue","Master Rules","Price Bands","Platform Fee Rules","Tax Rules","Discounts","Other Charges","Quote Simulator","Version History and Audit","Package Setup"];
const kinds:Record<string,string>={"Master Rules":"MASTER","Price Bands":"BAND","Platform Fee Rules":"FEE","Tax Rules":"TAX","Discounts":"DISCOUNT","Other Charges":"CHARGES"};
const fields:Record<string,string[]>={MASTER:["method","includedKm","includedHours","minimumKmPerDay","perKm","perHour","driverAllowance","waitingPerHour","nightCharge","cancellationReference","fallbackRateVersionId","fallbackVendorIds"],BAND:["minimum","recommended","maximum","autoMinimum","autoMaximum","smartMinimum","smartMaximum"],FEE:["fixed","percent","minimum","maximum","processingFixed","processingPercent","waive"],DISCOUNT:["name","fixed","percent","cap","vendorPercent","budget"]};
const label=(s:string)=>s.replace(/([A-Z])/g," $1").replace(/^./,v=>v.toUpperCase());
const cls="w-full rounded border border-slate-300 bg-white p-2 text-slate-900";
async function api(url:string,body?:unknown) { const r=await fetch(url,{credentials:"include",...(body ? {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)} : {})}); const j=await r.json(); if(!r.ok || !j.success) throw new Error(j.message || "Request failed"); return j.data; }
export default function PricingWorkbench() {
  const [data,setData]=useState<Row|null>(null),[tab,setTab]=useState(tabs[0]),[vendor,setVendor]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const [service,setService]=useState("LOCAL_POINT_TO_POINT"),[category,setCategory]=useState(""),[city,setCity]=useState(""),[fare,setFare]=useState(""),[smart,setSmart]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState("");
  const [packageName,setPackageName]=useState(""),[origin,setOrigin]=useState(""),[destination,setDestination]=useState(""),[area,setArea]=useState("");
  const [rule,setRule]=useState(""),[selectedPackages,setSelectedPackages]=useState<string[]>([]),[selectedRates,setSelectedRates]=useState<string[]>([]),[reason,setReason]=useState(""),[search,setSearch]=useState("");
  const [preview,setPreview]=useState<FareDetailsValue|null>(null),[vehicle,setVehicle]=useState(""),[distance,setDistance]=useState(""),[hours,setHours]=useState(""),[clone,setClone]=useState(false);
  const [policy,setPolicy]=useState<Row>({key:"",name:"",expectedVersion:0}),[values,setValues]=useState<Row>({}),[entries,setEntries]=useState<Row[]>([]);
  const load=useCallback(async()=>{try{setData(await api(`/api/pricing/manage${vendor ? `?vendorId=${encodeURIComponent(vendor)}` : ""}`));}catch(e){setError((e as Error).message);}},[vendor]);
  useEffect(()=>{void load();},[load]);
  const admin=data?.role==="SUPER_ADMIN",finance=data?.role==="FINANCE",vendorId=data?.vendorId || vendor;
  const rates:Row[]=useMemo(()=>(data?.rates || []).filter((r:Row)=>(!vendorId || r.vendorId===vendorId)&&(!category || r.vehicleCategory===category)&&(!service || r.service===service)&&(!city || r.city.includes(city.toLowerCase()))&&(!search || JSON.stringify(r).toLowerCase().includes(search.toLowerCase()))),[data,vendorId,category,service,city,search]);
  const rules:Row[]=(data?.rules || []).filter((r:Row)=>(!vendorId || r.vendorId===vendorId)&&(!category || r.vehicleCategory===category));
  const packages:Row[]=(data?.packages || []).filter((p:Row)=>p.pricingRuleId===rule);
  const bands:Row[]=(data?.policies || []).filter((p:Row)=>p.kind==="BAND"&&p.active&&(!p.service || p.service===service)&&(!p.vehicleCategory || p.vehicleCategory===category)&&(!p.city || p.city===city.toLowerCase()));
  async function run(fn:()=>Promise<unknown>) {setBusy(true);setError("");setNotice("");try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function action(r:Row,a:string){await run(async()=>{await api("/api/pricing/manage",{action:a,id:r.id,expectedVersion:r.version,reason});setNotice("Rate updated with audit evidence.");});}
  const simulate=useCallback(async (r?:Row,write=true)=>{const v=(data?.vehicles || []).find((v:Row)=>v.id===vehicle)||(data?.vehicles || []).find((v:Row)=>v.vendorId===(r?.vendorId || vendorId)&&v.category===(r?.vehicleCategory || category));if(!v)throw new Error("Select a vehicle for the preview.");const q=await api("/api/pricing/quote",{simulate:true,vendorId:r?.vendorId || vendorId,vehicleId:v.id,vehicleCategory:v.category,service:r?.service || service,city:r?.city || city,origin:r?.origin || origin,destination:r?.destination || destination,area:r?.area || area,pricingPackageId:r?.pricingPackageId || selectedPackages[0],at:new Date(from || Date.now()).toISOString(),...(distance ? {distanceKm:distance}:{}),...(hours ? {durationHours:hours}:{}),...(!r && fare ? {proposedFare:fare}:{}),...(r&&r.status!=="APPROVED" ? {draftRateId:r.id}:{})});if(write)setPreview(q.snapshot);return q.snapshot as FareDetailsValue;},[data,vehicle,vendorId,category,service,city,origin,destination,area,selectedPackages,from,distance,hours,fare]);
  // Preview requests are debounced and computed entirely on the server.
  useEffect(()=>{
    if (!fare || !vendorId || !category || !service || !from || !["Vendor Rate Cards","Route Pricing"].includes(tab)) return;
    let cancelled=false;
    const timer=setTimeout(()=>{void simulate(undefined,false).then(value=>{if(!cancelled){setPreview(value);setError("");}}).catch(e=>{if(!cancelled){setPreview(null);setError(e.message);}});},500);
    return()=>{cancelled=true;clearTimeout(timer);};
  },[fare,vendorId,category,service,from,tab,simulate]);
  async function draft(){if(!rule || !from)throw new Error("Select a rate card and Effective From.");for(const id of (selectedPackages.length ? selectedPackages:[null])){const pkg=packages.find(p=>p.id===id);const previous=(data?.rates || []).filter((r:Row)=>r.pricingRuleId===rule&&r.service===service&&r.pricingPackageId===id&&(id || r.city===city.toLowerCase())).sort((a:Row,b:Row)=>b.version-a.version)[0];const saved=await api("/api/pricing/manage",{action:"draft",pricingRuleId:rule,pricingPackageId:id,service,city:pkg?.city || city,origin,destination,area,fare,smartReturnFare:smart,effectiveFrom:new Date(from).toISOString(),effectiveTo:to ? new Date(to).toISOString():null,expectedVersion:previous?.version || 0});await simulate(saved);}setNotice("Draft saved. Review the price preview, then submit for approval.");}
  const kind=kinds[tab],policies:Row[]=(data?.policies || []).filter((p:Row)=>p.kind===kind),writable=admin||(finance&&["FEE","TAX","DISCOUNT"].includes(kind));
  function edit(p:Row){setPolicy({...p,expectedVersion:p.version});if(Array.isArray(p.data))setEntries(p.data);else setValues(p.data);setCity(p.city);setService(p.service);setCategory(p.vehicleCategory);setFrom(new Date(Date.now()+3600000).toISOString().slice(0,16));}
  const field=(name:string,value:string,set:(s:string)=>void,type="text")=><label key={name}>{name}<input type={type} className={cls} value={value} onChange={e=>set(e.target.value)}/></label>;
  return <main className="mx-auto max-w-7xl space-y-5 p-6 text-slate-900"><header><h1 className="text-3xl font-bold">Pricing Engine</h1><p className="text-slate-600">Set your fare, review the customer price and preserve every approved version.</p></header>{error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}{notice&&<p role="status" className="rounded bg-green-50 p-3">{notice}</p>}{!data ? <p>Loading pricing…</p>:<>
    <nav aria-label="Pricing sections" className="flex flex-wrap gap-2">{tabs.filter(t=>admin||finance||!["Approval Queue","Master Rules","Platform Fee Rules","Tax Rules","Discounts","Other Charges"].includes(t)).map(t=><button key={t} onClick={()=>{setTab(t);setPolicy({key:"",name:"",expectedVersion:0});setValues({});setEntries([]);}} className={`rounded px-3 py-2 text-sm ${tab===t ? "bg-slate-900 text-white":"bg-slate-100"}`}>{t}</button>)}</nav>
    <div className="grid gap-3 md:grid-cols-4">{(admin||finance)&&<label>Vendor<select className={cls} value={vendor} onChange={e=>{setVendor(e.target.value);setRule("");}}><option value="">All vendors</option>{data.vendors.map((v:Row)=><option key={v.id} value={v.id}>{v.companyName}</option>)}</select></label>}<label>Service<select className={cls} value={service} onChange={e=>setService(e.target.value)}><option value="">All services</option>{data.services.map((s:string)=><option key={s}>{s}</option>)}</select></label><label>Vehicle category<select className={cls} value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{data.categories.map((s:string)=><option key={s}>{s}</option>)}</select></label>{field("Market / City",city,setCity)}</div>
    {tab==="Pricing Overview"&&<><div className="grid gap-3 md:grid-cols-4">{Object.entries(data.overview).map(([k,v])=><div key={k} className="rounded border p-4"><p className="text-sm">{label(k)}</p><strong className="text-2xl">{typeof v==="boolean" ? v ? "Configured":"Required":String(v)}</strong></div>)}</div><p>Counts include all database records. Packages without a dedicated approved version need review; a default rate may apply. Configuration status indicates a policy exists, not complete market coverage.</p></>}
    {["Vendor Rate Cards","Route Pricing"].includes(tab)&&<section className="space-y-4 rounded border p-4"><h2 className="text-xl font-bold">Your Fare</h2><div className="grid gap-3 md:grid-cols-3"><label>Rate card<select className={cls} value={rule} onChange={e=>{setRule(e.target.value);setSelectedPackages([]);}}><option value="">Select a card</option>{rules.map(r=><option value={r.id} key={r.id}>{r.vehicleCategory} · {r.pricingType} · {r.tripType}</option>)}</select></label>{field("Your Fare (₹)",fare,setFare)}{field("Smart Return special fare (optional)",smart,setSmart)}</div><button disabled={busy||!vendorId||!category} className="rounded border p-2" onClick={()=>run(async()=>{const r=await api("/api/pricing/manage",{action:"card",vendorId,vehicleCategory:category});setRule(r.id);})}>Create or select category card</button>
    <div className="grid gap-3 md:grid-cols-3">{field("Origin",origin,setOrigin)}{field("Destination",destination,setDestination)}{field("Airport / Area",area,setArea)}</div><details className="rounded border p-3"><summary>Add a route or package to this card</summary><div className="space-y-3">{field("Package or contract name",packageName,setPackageName)}<label>Vehicle<select className={cls} value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">Select vehicle</option>{data.vehicles.filter((v:Row)=>v.vendorId===vendorId&&(!category||v.category===category)).map((v:Row)=><option key={v.id} value={v.id}>{v.registrationNumber}</option>)}</select></label><button disabled={busy} className="rounded border p-2" onClick={()=>run(async()=>{const p=await api("/api/pricing/manage",{action:"package",pricingRuleId:rule,vehicleId:vehicle,name:packageName,service,city,origin,destination,area,fare});setSelectedPackages([p.id]);setNotice("Package saved. Submit its fare version for approval.");})}>Add package</button></div></details><fieldset><legend>Apply to routes / areas / packages</legend>{packages.length ? packages.map(p=><label className="mr-4 inline-block" key={p.id}><input type="checkbox" checked={selectedPackages.includes(p.id)} onChange={e=>setSelectedPackages(e.target.checked ? [...selectedPackages,p.id]:selectedPackages.filter(id=>id!==p.id))}/> {p.city} · {p.packageName}</label>):<p>No packages on this card. Submit a city/default rate or use Package Setup.</p>}</fieldset>{bands.map(b=><p key={b.id}>Minimum ₹{b.data.minimum} · Recommended ₹{b.data.recommended} · Maximum ₹{b.data.maximum} · Auto-approval ₹{b.data.autoMinimum}–₹{b.data.autoMaximum}</p>)}{!bands.length&&<p>No band configured. Manual approval with a reason is required.</p>}<div className="grid gap-3 md:grid-cols-2">{field("Effective From",from,setFrom,"datetime-local")}{field("Effective To (optional)",to,setTo,"datetime-local")}</div><label className="block"><input type="checkbox" checked={clone} onChange={e=>setClone(e.target.checked)}/> I confirm copying a fare from another service or category</label><select className={cls} disabled={!clone} value="" onChange={e=>{const r=data.rates.find((r:Row)=>r.id===e.target.value);if(r)setFare(r.fare);}}><option value="">Clone a fare…</option>{data.rates.map((r:Row)=><option key={r.id} value={r.id}>{r.service} · {r.vehicleCategory} · ₹{r.fare}</option>)}</select><button disabled={busy} className="rounded bg-slate-900 px-4 py-2 text-white" onClick={()=>run(draft)}>Save draft & preview</button></section>}
    {kind&&<section className="space-y-4 rounded border p-4"><h2 className="text-xl font-bold">{tab}</h2>{!policies.length&&<p>No rules configured.</p>}{policies.map(p=><article key={p.id} className="rounded bg-slate-50 p-3"><b>{p.name} · v{p.version}</b><p>{p.city||"All markets"} · {p.service||"All services"} · {p.active ? "Active":"Inactive"} · {new Date(p.effectiveFrom).toLocaleString()}</p><pre className="overflow-auto text-xs">{JSON.stringify(p.data,null,2)}</pre>{writable&&<button className="underline" onClick={()=>edit(p)}>Create next version</button>}</article>)}{writable&&<><div className="grid gap-3 md:grid-cols-3">{["key","name","route"].map(k=>field(label(k),policy[k]||"",s=>setPolicy({...policy,[k]:s})))}</div><p>Uses the selected market, service, category and vendor. Clear filters for global applicability. Route format: origin|destination.</p>{fields[kind]&&<div className="grid gap-3 md:grid-cols-3">{fields[kind].map(k=>k==="waive" ? <label key={k}>Waive fee<select className={cls} value={String(values.waive ?? "")} onChange={e=>setValues({...values,waive:e.target.value==="true"})}><option value="">Select</option><option value="false">No</option><option value="true">Yes</option></select></label>:field(label(k),values[k]||"",s=>setValues({...values,[k]:k==="fallbackVendorIds" ? s.split(",").map(v=>v.trim()).filter(Boolean):s})))}</div>}{kind==="MASTER"&&<p>Method: FIXED, PER_KM or PER_HOUR. Use explicit zeroes for rules that do not apply. Market fallback is optional: specify an approved version ID and a comma-separated vendor allowlist.</p>}
    {["TAX","CHARGES"].includes(kind)&&<><p>{kind==="TAX" ? "Configure tax bases explicitly. An empty published list records Finance's decision that no tax applies to this scope.":"Standard pass-through charges. Included charges do not increase the final amount."}</p>{entries.map((row,i)=><div className="grid gap-2 rounded border p-3 md:grid-cols-3" key={i}>{(kind==="TAX" ? ["name","rate","jurisdiction"]:["name","amount"]).map(k=>field(label(k),row[k]||"",s=>setEntries(entries.map((x,n)=>n===i ? {...x,[k]:s}:x))))}{(kind==="TAX" ? ["deductVendorDiscount","deductPlatformDiscount"]:["vendorPayable","included"]).map(k=><label key={k}><input type="checkbox" checked={!!row[k]} onChange={e=>setEntries(entries.map((x,n)=>n===i ? {...x,[k]:e.target.checked}:x))}/>{label(k)}</label>)}{kind==="TAX"&&["VENDOR_FARE","PLATFORM_FEE","PASS_THROUGH"].map(c=><label key={c}><input type="checkbox" checked={(row.components||[]).includes(c)} onChange={e=>setEntries(entries.map((x,n)=>n===i ? {...x,components:e.target.checked ? [...(x.components||[]),c]:x.components.filter((s:string)=>s!==c)}:x))}/>{c}</label>)}<button onClick={()=>setEntries(entries.filter((_,n)=>n!==i))}>Remove</button></div>)}<button className="rounded border p-2" onClick={()=>setEntries([...entries,kind==="TAX" ? {components:[],deductVendorDiscount:false,deductPlatformDiscount:false}:{included:false,vendorPayable:false}])}>Add component</button></>}
    {field("Effective From",from,setFrom,"datetime-local")}{field("Effective To (optional)",to,setTo,"datetime-local")}<label className="block"><input type="checkbox" checked={policy.active!==false} onChange={e=>setPolicy({...policy,active:e.target.checked})}/> Active policy version</label><button disabled={busy} className="rounded bg-slate-900 p-2 text-white" onClick={()=>run(async()=>{await api("/api/pricing/manage",{...policy,action:"policy",kind,city,service,vehicleCategory:category,vendorId:vendor||"",data:["TAX","CHARGES"].includes(kind) ? entries:Object.fromEntries(Object.entries(values).filter(([,v])=>v!=="")),effectiveFrom:new Date(from).toISOString(),effectiveTo:to ? new Date(to).toISOString():null});setNotice("Policy version saved with audit evidence.");})}>Publish policy version</button></>}</section>}
    {tab==="Quote Simulator"&&<section className="space-y-3 rounded border p-4"><label>Vehicle<select className={cls} value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">Select vehicle</option>{data.vehicles.filter((v:Row)=>!vendorId||v.vendorId===vendorId).map((v:Row)=><option key={v.id} value={v.id}>{v.registrationNumber} · {v.category}</option>)}</select></label>{field("Trip date",from,setFrom,"datetime-local")}{field("Distance (km)",distance,setDistance)}{field("Duration (hours)",hours,setHours)}{field("Origin",origin,setOrigin)}{field("Destination",destination,setDestination)}{field("Airport / Area",area,setArea)}<button onClick={()=>run(()=>simulate())} className="rounded border p-2">Calculate price</button></section>}
    {preview&&<section className="rounded border bg-slate-50 p-4"><h2 className="font-bold">Server-calculated preview</h2><FareDetails value={preview} internal/></section>}
    {["Vendor Rate Cards","Route Pricing","Approval Queue","Version History and Audit"].includes(tab)&&<section className="space-y-3">{field("Search rates, routes or status",search,setSearch)}{field("Approval / rejection reason",reason,setReason)}<div className="flex gap-2">{["submit",...(admin ? ["approve","reject"]:[]),"deactivate"].map(a=><button disabled={busy||!selectedRates.length} key={a} className="rounded border p-2" onClick={()=>run(async()=>{const result=await api("/api/pricing/manage",{action:"bulk",operation:a,reason,items:rates.filter(r=>selectedRates.includes(r.id)).map(r=>({id:r.id,version:r.version}))});setNotice(result.map((r:Row)=>`${r.id}: ${r.success ? "Updated":r.message}`).join("; "));})}>Bulk {a}</button>)}</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Select","Service / Route","Version","Your Fare","Status","Effective dates","Actions"].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{rates.filter(r=>tab!=="Approval Queue"||r.status==="PENDING").map(r=><tr className="border-t" key={r.id}><td><input type="checkbox" checked={selectedRates.includes(r.id)} onChange={e=>setSelectedRates(e.target.checked ? [...selectedRates,r.id]:selectedRates.filter(id=>id!==r.id))}/></td><td className="p-2">{r.service}<br/>{r.city} {r.origin} → {r.destination} {r.area}</td><td>{r.version}</td><td>₹{r.fare}<br/><small>Previous: {(data.rates as Row[]).filter(old=>old.scopeKey===r.scopeKey&&old.version<r.version).sort((a,b)=>b.version-a.version)[0]?.fare || "No previous version"}</small><br/>{r.smartReturnFare&&`Smart Return ₹${r.smartReturnFare}`}</td><td>{r.status}<br/>{r.reviewReason}</td><td>{new Date(r.effectiveFrom).toLocaleString()}<br/>{r.effectiveTo&&new Date(r.effectiveTo).toLocaleString()}</td><td className="space-x-2"><button className="underline" onClick={()=>run(()=>simulate(r))}>Preview</button>{r.status==="DRAFT"&&<button className="underline" onClick={()=>action(r,"submit")}>Submit</button>}{r.status==="PENDING"&&admin&&<><button className="underline" onClick={()=>action(r,"approve")}>Approve</button><button className="underline" onClick={()=>action(r,"reject")}>Reject</button></>}{["APPROVED","DRAFT","PENDING"].includes(r.status)&&<button className="underline" onClick={()=>action(r,"deactivate")}>Deactivate</button>}</td></tr>)}</tbody></table>{!rates.length&&<p className="p-4">No rate versions match these filters.</p>}</div><p className="text-xs">Detail views show up to 500 versions; overview counts include all records.</p></section>}
    {tab==="Version History and Audit"&&<section>{data.audit.map((a:Row)=><details key={a.id} className="border-b p-2"><summary>{new Date(a.createdAt).toLocaleString()} · {a.action} · {a.userId} · {a.entityId}</summary><pre className="overflow-auto text-xs">{JSON.stringify({previous:a.oldValue,new:a.newValue},null,2)}</pre></details>)}</section>}
    {tab==="Package Setup"&&<><p>Existing vehicle and route package setup. Publishing requires an approved rate version and configured fee, tax and charge policies.</p><LegacyPackages/></>}
    </>}</main>;
}
