/** Editorial planning notes keyed to the imported destination/zone universe.
 * These are journey-planning decisions, not claims about traffic, operating hours,
 * distances, fleet, fares or access. Source facts remain in phase1-source-data.json.
 */
export const destinationAdvice: Record<string, string> = {
  Mumbai: "A Mumbai city drop, a meeting in a particular suburb and an airport drop are different endpoints. Put the actual meeting address on the trip and decide whether you need the car retained between appointments.",
  "Navi Mumbai": "Specify the Navi Mumbai locality before requesting a car. A city address and Navi Mumbai International Airport are different destinations; the airport name should appear explicitly if that is where the journey ends.",
  Lonavala: "For a Lonavala stay, decide whether the car is only taking you to your accommodation. Visits elsewhere in the Lonavala–Khandala plan need their own stop list and waiting arrangement.",
  Nashik: "A Nashik drop does not cover a Trimbakeshwar visit or an onward Shirdi journey automatically. Separate your city address, any temple stops and the final return when describing the trip.",
  Mahabaleshwar: "Choose whether Mahabaleshwar is your stay location or the start of sightseeing. If Panchgani or Pratapgad is part of the holiday, include it explicitly rather than treating a hotel transfer as a circuit.",
  Shirdi: "Decide whether you need a drop in Shirdi or a car waiting for your return. Shani Shingnapur is a separate visit; include both destinations if that is your pilgrimage plan.",
  Kolhapur: "Keep the Kolhapur address distinct from additional visits to Jyotiba or Narsobawadi. If your party is staying in the city, state whether the car is released on arrival or retained for those visits.",
  Thane: "Use the Thane meeting or accommodation address as the final destination. If members of your group need separate drops, list them before comparing a direct transfer with a return arrangement.",
  Alibaug: "For an Alibaug visit, identify the road-accessible accommodation or meeting point. A plan extending to Murud-Janjira needs a separate stop, and transport by water should not be assumed to be included.",
  Ratnagiri: "Make the Ratnagiri stay and any Ganpatipule visit separate parts of your request. Decide whether to retain the same vehicle between them or arrange only the point-to-point transfers.",
  Satara: "A Satara city drop and a Kaas sightseeing plan serve different needs. If Kaas is intended, confirm access independently and ask for the road arrangement to cover that visit as well as the city.",
  Panchgani: "If Panchgani is your accommodation base, start with that address. A visit to Mahabaleshwar or Pratapgad should be written into the travel plan instead of being assumed within the arrival transfer.",
  Karjat: "Share the property or host's meeting instructions for your Karjat visit. If the final approach requires a different meeting point, settle that before departure instead of relying on the destination name alone.",
  Matheran: "Confirm the permitted vehicle endpoint for your Matheran booking and arrange any onward access separately. Do not assume the cab can reach every accommodation entrance or remain with you throughout a visit.",
  "Chhatrapati Sambhajinagar": "Chhatrapati Sambhajinagar and Aurangabad refer to the same city hub in this guide. Ajanta, Ellora and Grishneshwar are individual visits, so a city transfer should not stand in for a full heritage circuit.",
  Solapur: "Use the Solapur address for a city arrival. If the journey continues to Tuljapur, Pandharpur or Akkalkot, list those destinations separately and choose a return plan that covers the complete pilgrimage.",
  Sangli: "Decide whether your final drop is in Sangli or whether Miraj is also part of the trip. A second appointment or onward connection should be included before deciding to release the car.",
  Goa: "Goa is too broad to be a precise drop address. Provide the town and accommodation, and distinguish that arrival transfer from local touring or a later journey to an airport.",
  Bhimashankar: "Discuss the intended meeting point and any mobility needs for the Bhimashankar visit. A car retained for your return is a different request from a drop, and darshan arrangements are separate.",
  Trimbakeshwar: "If your Trimbakeshwar plan also includes Nashik, say whether Nashik is a visit, a stay or the final drop. Keep temple time separate from the agreed road journey and return pickup.",
  Jejuri: "For a Jejuri visit, agree where passengers leave and meet the car. If Narayanpur or Prati Balaji is also intended, include those stops by name before asking for a circuit arrangement.",
  Tuljapur: "Settle whether the Tuljapur visit ends with a local drop or a return to your origin. If combining it with another pilgrimage destination, request the complete stop list rather than a single-temple transfer.",
  Pandharpur: "Plan the Pandharpur drop and post-visit meeting point together. A return booking should reflect when the group expects to be ready, without treating temple access or waiting time as guaranteed.",
  Ahmednagar: "An Ahmednagar city visit and onward travel toward another destination need different trip details. Use the exact meeting address and include any continuation before comparing a drop with a return booking.",
  Ganpatipule: "Clarify whether Ganpatipule is the final stay or a visit within a Ratnagiri plan. Agree the vehicle's waiting arrangement independently of accommodation and temple arrangements.",
  Khandala: "For Khandala, decide whether the booking is an arrival transfer or includes visits in Lonavala. Keep the final pickup after sightseeing explicit so the return is not left to an assumed waiting period.",
  "Mumbai Airport": "Identify Mumbai's Chhatrapati Shivaji Maharaj International Airport on the flight booking. Do not substitute Navi Mumbai airport, and confirm terminal and pickup instructions separately from this city-to-airport road search.",
  Bengaluru: "Provide the Bengaluru neighbourhood and final address, especially when the trip ends at an appointment rather than accommodation. If an airport connection is intended, name the airport explicitly before confirming the journey.",
  Hyderabad: "Distinguish a Hyderabad city address from Hyderabad Airport. For a visit with several appointments, list the drop sequence and decide whether the car is needed beyond the initial arrival.",
  Vapi: "If the Vapi journey is for a work visit, obtain the host's entrance and visitor instructions. A meeting that finishes later needs an agreed return pickup rather than an assumed car waiting outside.",
  Pune: "Choose the Pune pickup or drop zone that matches your actual address, such as Kharadi, Hinjewadi or the station area. A city transfer does not include a local package or onward tour automatically.",
  Igatpuri: "If Igatpuri is part of a Bhandardara plan, distinguish the stay from the additional visit. Confirm where luggage will remain and whether the vehicle should stay with your party between transfers.",
  Surat: "For a Surat appointment, identify the final premises and when you expect to be ready to leave. If the return date is uncertain, compare a one-way arrival with a separately planned return.",
  Palghar: "Give the precise Palghar meeting address rather than only the broader destination name. If your host proposes a different handover point, put that into the travel instructions before setting out.",
  Daman: "For a Daman stay, specify the accommodation and whether you need local visits after arrival. A transfer ending at the property should not be treated as a car retained throughout the holiday.",
  Silvassa: "Separate a Silvassa arrival from travel between multiple venues during your stay. The car and luggage requirements can differ if everyone is dropped once versus remaining together for several visits.",
  Ahmedabad: "Share the Ahmedabad final address and any fixed appointment time when planning departure. For a return journey, enter the actual return date instead of treating the arrival quote as covering both legs.",
  Saputara: "Decide which Saputara stay or meeting point anchors the visit. Ask whether the vehicle is retained during your leisure time; attraction activities and access are not part of a point-to-point cab request.",
  Bhandardara: "Choose the Bhandardara stay location before planning the car. An onward Igatpuri visit changes the stop list, and luggage should be considered if the group travels between accommodation and sightseeing.",
  Vadodara: "For Vadodara, record each business or family drop separately if the party is splitting up. A single destination quote should be reviewed again when an additional venue is added.",
  "Shani Shingnapur": "Treat Shani Shingnapur as its own stop even when paired with Shirdi. Agree the visit order and final drop so a quote for either individual transfer is not mistaken for the combined pilgrimage.",
  "Pune Airport": "Use Pune Airport, PNQ, as the explicit destination and check the flight details yourself. A nearby Viman Nagar address is not the same endpoint, and airport waiting or parking must be confirmed separately.",
  Panvel: "Clarify whether the Panvel destination is an address, a transport connection or onward travel. The scheduled arrival of another service should leave room for passengers to reach the agreed cab meeting point.",
  Sinnar: "If your Sinnar visit is tied to an appointment, request the exact entrance from the host. Decide how a delayed finish would affect the return before choosing between a drop and a retained car.",
  Manmad: "If connecting with a train at Manmad, keep the station meeting point and train details in your plan. The booked cab pickup should be when passengers are ready, not merely the train's scheduled arrival.",
  Malegaon: "Use the complete Malegaon address for the destination and identify any additional passenger drops. Agree which address ends the trip, particularly when relatives or colleagues are travelling together.",
  Dhule: "For a Dhule drop followed by another journey, distinguish the handover point from the onward destination. Booking the first leg does not reserve a car for the next stage.",
  Jalgaon: "A Jalgaon visit with an overnight stay needs a clear decision about retaining the vehicle. Specify the stay address and next departure date rather than relying on a single arrival booking.",
  Indore: "If travelling to Indore with a planned Ujjain visit, include the second destination explicitly. A city drop and a multi-stop return have different requirements for dates and vehicle retention.",
  Ujjain: "For the Ujjain visit, settle the post-visit pickup point and return day before choosing a car. Temple arrangements and any Indore stop need their own confirmation beyond the road transfer.",
  "Shirdi Airport": "A Shirdi Airport transfer ends at the airport specified in the request, not at the temple area. Confirm flight and road pickup details independently and name any Shirdi town visit as an additional stop.",
  Ajanta: "Keep the Ajanta cave visit distinct from Ellora when requesting transport. Confirm attraction access for the intended date separately; the car arrangement should state where the driver waits and where the journey ends.",
  Ellora: "If Ellora and Grishneshwar are both planned, name them as separate visits. Cave admission and a temple visit are separate from the cab booking, even when the same car is retained.",
  Grishneshwar: "Decide whether Grishneshwar is a standalone temple visit or part of an Ellora and Sambhajinagar circuit. Agree the return meeting point without assuming darshan timing is controlled by the transport booking.",
  Jalna: "For a Jalna work or family visit, choose the final address before comparing journey types. A car returning with the group needs a stated return date and any intermediate visits in the request.",
  Daulatabad: "If the Daulatabad plan includes a heritage visit, separate time spent visiting from the road transfer. Confirm the road meeting point and whether the driver waits or the booking ends on arrival.",
  Paithan: "Clarify the particular Paithan venue you want to reach and any additional local visit. A city-name destination alone cannot describe a multi-stop outing or the pickup after it.",
  Beed: "Give the Beed host or venue address and decide how passengers will return. If the group stays overnight, the return date and whether the vehicle is retained should be settled before booking.",
  Nanded: "For Nanded, identify the place of stay and the visit address separately if they differ. Keep time at your destination distinct from car waiting, especially when the return is on another day.",
  Latur: "List the Latur arrival address and any onward passenger drops in order. If your schedule changes after an appointment, review the agreed return arrangement rather than extending a one-way booking informally.",
  Nagpur: "Nagpur city, an airport connection and a road journey onward to Wardha need distinct endpoints. If combining them, specify each stage so the vehicle request reflects the complete plan.",
  Akola: "For an Akola visit, establish whether the driver is released at the first address. If several meetings are planned, list those venues and the final pickup rather than using only the city name.",
  Parbhani: "Choose a precise Parbhani drop when coordinating with a host or onward service. Share the expected handover time and decide whether the same vehicle must be available for the return.",
  "Aundha Nagnath": "Aundha Nagnath is one named stop in the supplied Panch Jyotirlinga plan. A standalone temple transfer does not include the other four visits; use the circuit guide for a combined road request.",
  Wardha: "For Wardha, distinguish a direct regional drop from a day with several visits. If you expect to return to Nagpur, make the return part of the search instead of assuming the outbound car waits.",
  Bhandara: "If your Bhandara trip involves collecting or dropping different passengers, agree one ordered address list. The last handover point should match the booked destination rather than an unstated continuation.",
  Amravati: "An Amravati city arrival and an onward Chikhaldara visit are different plans. Keep the city appointment or stay separate from additional leisure travel when deciding whether to retain a car.",
  Chhindwara: "For Chhindwara, get the complete destination address from your host and state any onward visit. If returning on another date, compare the complete return plan rather than only the outward transfer.",
  Yavatmal: "Set the Yavatmal final drop and any waiting expectation before requesting a vehicle. For an appointment with an uncertain finish, decide how you want to handle the return pickup.",
  Chandrapur: "A Chandrapur address should not stand in for a Tadoba visit. If wildlife travel is intended, specify the exact confirmed meeting location and keep admission arrangements separate from the road booking.",
  Pench: "Use the confirmed accommodation or entry meeting location for a Pench journey. Reserve any wildlife activity independently; transport to the area does not guarantee entry, a safari or a sighting.",
  Ramtek: "For a Ramtek visit, clarify the car's drop and later meeting point. If other visits are planned on the return, name them before comparing a direct transfer with a round trip.",
  Tadoba: "Confirm the exact Tadoba meeting or accommodation location against your activity reservation. The cab is for the road journey and must not be treated as a safari vehicle or an entry reservation.",
  Jabalpur: "For Jabalpur, separate your arrival address from subsequent sightseeing or appointments. If the car is retained over a stay, the return date and complete travel scope need to be in the request.",
  Saoner: "Use the specific Saoner venue for a regional drop. A quick passenger handover and a car waiting through a visit need different arrangements even when the destination city is the same.",
  Gondia: "If Gondia is an onward travel connection, name the handover point and allow for reaching the next service. If it is a stay, use the accommodation address as the actual end of the cab journey.",
  Seoni: "Do not use a Seoni city drop as shorthand for an unnamed wildlife or accommodation destination. Confirm the exact address and disclose any continuation before selecting a one-way or return service.",
  Balaghat: "For Balaghat, identify who is meeting the group and the agreed address. A later return pickup should be scheduled separately in the plan, particularly if passengers are staying in different places.",
  Raipur: "When the Raipur trip is for several meetings, collect the venue addresses before booking. Specify whether the car ends at the first drop or remains part of a dated return journey.",
  Chikhaldara: "Choose the Chikhaldara stay and intended sightseeing scope before arranging transport. A car that drops your group at accommodation is not automatically retained for outings or the journey home.",
  Bhopal: "Give the Bhopal final venue and any fixed arrival requirement when planning the trip. If the group returns together after a stay, the return day should be included from the start.",
  Betul: "For Betul, clarify whether your booking ends with a passenger drop or a visit followed by return. Any continuation beyond the agreed destination needs to be reflected in the travel request.",
  Warora: "If the Warora trip is a work visit, use the host's entrance instructions rather than a broad locality. Discuss the return pickup after the appointment before deciding to keep the vehicle.",
  Umred: "State the exact Umred destination, especially if your plan extends beyond a town address. Any attraction or activity reservation is independent of the cab, and the road endpoint should match that arrangement.",
  Katol: "For a Katol visit, agree how the party meets the driver after the first drop. Choose a return request if the same vehicle is needed, instead of relying on the duration of the visit being predictable.",
  Pachmarhi: "Identify the Pachmarhi stay and discuss local sightseeing separately from the arrival journey. Confirm current access arrangements yourself and avoid assuming all visits can be covered by a single transfer.",
  Akkalkot: "If combining Akkalkot with Ganagapur, name both stops and the final return city. A car to Akkalkot alone is not the two-destination pilgrimage circuit described in the tour guide.",
  "Dharashiv (Osmanabad)": "Use both Dharashiv and Osmanabad in the address if that helps your host identify the intended destination. Confirm the particular venue rather than creating separate trips for the two city names.",
  "Hyderabad Airport": "Name Hyderabad Airport explicitly instead of using a Hyderabad city drop. Use the flight booking to verify the endpoint and agree passenger readiness, luggage and any waiting requirements before travel.",
  Baramati: "For Baramati, gather the appointment or host address and clarify whether other stops are required. A return after the visit should use a return search with the correct date.",
  "Kalaburagi (Gulbarga)": "Kalaburagi and Gulbarga appear together in the supplied destination name. Use the host's precise address to avoid ambiguity and decide whether any onward travel is included before selecting the car.",
  "Vijayapura (Bijapur)": "Confirm the intended address under Vijayapura or Bijapur with your host. If the visit involves more than the arrival venue, set out those stops separately from the one-way city drop.",
  Barshi: "For a Barshi family or work visit, decide whether all passengers have the same final address. Multiple handovers should be stated before treating the journey as a single direct drop.",
  Mangalwedha: "If Mangalwedha is one part of a pilgrimage plan, list the other visits by name. Agree where passengers rejoin the car and where the journey finishes after the final stop.",
  Akluj: "Use the Akluj venue address and a contact's meeting instructions for the final approach. If the booking is for a group visit, decide whether the car waits or is released on arrival.",
  Miraj: "A Miraj destination should be specified separately from a Sangli visit. For a connection or appointment, provide the actual handover location and whether your party needs a return vehicle.",
  Belagavi: "Confirm the Belagavi address even if your host uses the Belgaum name. A city arrival and onward travel need distinct stops, with the final return date included when requesting a round trip.",
  Badami: "For a Badami heritage visit, separate the accommodation drop from the places you plan to explore. Attraction access and time inside each site remain independent of the car arrangement.",
  Hampi: "Give the Hampi stay or agreed road meeting point rather than only the sightseeing destination. Decide how transport between visits is arranged; site admission and a fixed sightseeing itinerary are not implied.",
  Karad: "For Karad, identify the final passenger handover and any additional venue before selecting the trip. A regional drop can end there, while a retained car needs a clear return plan.",
  Ichalkaranji: "If travelling to Ichalkaranji for meetings, collect the venue entrance details and expected finish. Multiple appointments should be listed so a single drop is not confused with transport through the working day.",
  Hubballi: "Choose the Hubballi final address and state separately if Dharwad is also part of the journey. A booking to one city should not be treated as automatically covering visits in the other.",
  Panaji: "For a Panaji drop, give the accommodation or meeting address within the broader Goa plan. Any further travel to another stay or airport needs its own explicit destination and arrangement.",
  Nipani: "Use the Nipani host's address for the handover and decide whether the party is returning together. If passengers continue onwards, keep that continuation separate from the booked endpoint.",
  Sawantwadi: "If Sawantwadi is a stop before a further leisure destination, include the next destination in the request. Decide whether luggage stays in a retained vehicle or leaves with the party at the drop.",
  Tarkarli: "Identify the Tarkarli accommodation and the amount of luggage before choosing a category. Local activities and any further sightseeing are separate from the arrival transfer unless expressly arranged.",
  Amboli: "For an Amboli visit, agree the stay or road meeting point and the return pickup. Do not assume a transfer includes waiting during every leisure stop; describe the outing you intend.",
  Chiplun: "Choose the Chiplun final address and distinguish an overnight stay from a brief visit. If the journey continues after the stop, include that travel rather than treating it as part of the first drop.",
  Gokarna: "Provide the Gokarna accommodation's road meeting instructions and your luggage needs. A cab transfer does not include activities, attraction entry or transport throughout the stay unless separately agreed.",
  Dharwad: "For Dharwad, confirm the particular venue and whether Hubballi is an additional stop. Settle the last drop and return day before comparing a direct arrival with a multi-stop journey.",
  Dandeli: "Use the Dandeli accommodation or activity provider's meeting point for transport planning. Activity slots and permissions need their own confirmation; the cab booking covers only the agreed road journey.",
};

// Specific pickup decisions; no inferred airport distances or unverified zone classifications.
export const areaAdvice: Record<string, string> = {
  "Pimpri-Chinchwad": "Use the specific locality and property within Pimpri-Chinchwad. If passengers board at different addresses, collect the full pickup sequence before choosing a local package or an intercity drop.",
  "Viman Nagar / Pune Airport": "Choose between a Viman Nagar address and an actual Pune Airport pickup. The combined zone label is a planning aid; a flight arrival needs the airport identity and passenger meeting instructions.",
  Baner: "If leaving from a Baner residence or office, share its entrance with the driver. When colleagues join from another address, include that collection before the outward journey rather than assuming a single pickup.",
  Hinjewadi: "Give the Hinjewadi building or campus gate instead of only a locality name. For a workday trip, decide whether the car is needed between appointments or only after the final meeting.",
  "Koregaon Park": "For a Koregaon Park hotel or meeting, use the property's own pickup instructions. Keep checkout and luggage collection in mind when selecting the time passengers will actually be ready.",
  Kharadi: "Use the Kharadi office, hotel or residence entrance as the meeting point. If a business appointment precedes an intercity departure, allow for collecting luggage and meeting the car after the appointment.",
  "Wadgaon Sheri": "Provide the full Wadgaon Sheri address, including a building name where applicable. If your intended destination is an airport, identify it separately instead of treating the pickup locality as an airport booking.",
  Shivajinagar: "A Shivajinagar street address and a transport-terminal meeting are different pickups. Specify which you mean and choose the time after passengers have reached the agreed exit or entrance.",
  "Deccan Gymkhana": "For a Deccan Gymkhana visit, identify the meeting premises and where the car can collect the party. If the day includes other venues, compare a local package with a single drop.",
  Swargate: "If meeting after a bus arrival at Swargate, confirm the particular arrival point. Share a passenger-ready time rather than using a timetable arrival as an automatic cab pickup.",
  "Pune Railway Station / Camp": "Decide whether pickup is at Pune Railway Station or a Camp address. Station arrivals need an agreed exit; a hotel pickup should use the hotel's own entrance and checkout plan.",
  "Hadapsar / Magarpatta": "Specify Hadapsar or the actual Magarpatta premises in the full address. If entering a managed property, obtain the meeting instructions so the driver is not left searching for a generic zone centre.",
  Wakad: "For a Wakad pickup involving a family group, gather passengers at one agreed address where possible. If several collections are necessary, declare them before comparing the onward trip.",
  Aundh: "Use an identifiable Aundh property entrance and the complete address. A visit that ends elsewhere in Pune needs a stated final drop, especially when comparing local use with a one-way journey.",
  Balewadi: "If leaving after an event or appointment in Balewadi, agree a practical meeting point with your host. Schedule the cab for passenger readiness and include any onward luggage collection.",
  Andheri: "Narrow the Andheri pickup to the actual address and side used by your host. Do not rely on the broad locality label when the group is assembling from several buildings.",
  "Andheri East / Airport": "Distinguish an Andheri East property from an airport terminal meeting. A nearby address does not give the driver flight details, terminal instructions or an airport waiting arrangement.",
  "South Mumbai": "Name the specific South Mumbai venue before requesting the ride. If sightseeing and an intercity departure share the day, list the separate stops and where luggage is collected.",
  "Andheri West": "For Andheri West, use the venue entrance and confirm whether passengers meet together. If another collection is on the plan, include its full address rather than assuming it belongs to the same pickup.",
  Bandra: "Use the exact Bandra address and clarify the meeting location with the host. Bandra West and BKC have separate guides here, so choose the one matching your actual starting point.",
  Sakinaka: "For a Sakinaka hotel or workplace, ask which entrance the driver should use. Set the pickup after your party has checked out or finished work, with luggage ready to load.",
  "Santacruz East": "Enter Santacruz East with the full property address. If the trip involves a flight, keep the airport destination explicit and avoid substituting a neighbourhood pickup for a terminal meeting.",
  Kurla: "A Kurla address and a railway-related meeting need different instructions. Specify the building or agreed station exit and tell the driver where the passengers will actually be waiting.",
  Goregaon: "For a Goregaon appointment or stay, confirm the precise premises before setting pickup. If a group is leaving an event together, agree one meeting point and account for everyone's luggage.",
  "Bandra West": "Give the Bandra West venue and entry instructions, especially when several people are joining. Do not substitute a broad Bandra or BKC location for the actual collection address.",
  Colaba: "If collecting from a Colaba stay, use the accommodation's pickup point and checkout time. A sightseeing outing before departure needs a stop list rather than only an intercity destination.",
  Powai: "For a Powai building or campus pickup, share the designated meeting entrance. Decide whether the car is for a single departure or needed between venues during the day.",
  Juhu: "When leaving a Juhu hotel or event, confirm where vehicles meet guests. Set the departure after the group is ready and state any additional collection before the final destination.",
  "Bandra Kurla Complex (BKC)": "Use the specific BKC office or venue and visitor meeting instructions. If appointments span several buildings, a local package may fit the day better than treating each visit as part of one drop.",
  "Vile Parle": "Identify the Vile Parle property and meeting entrance. If the journey starts at an airport instead, use the airport identity and passenger instructions rather than this locality as a substitute.",
  "Shalimar Chowk": "Agree the precise meeting premises around Shalimar Chowk. A named shop, hotel or host address is more useful for collection than expecting both parties to find each other at a broad junction.",
  "Mumbai Agra Road": "Provide the property address on Mumbai Agra Road and its approach instructions. The road name covers a travel zone and should not be used as a single assumed pickup point.",
  "MIDC Ambad": "If the pickup is inside business premises in MIDC Ambad, ask for the visitor gate and meeting rules. Include any second worksite visit before selecting the day's journey.",
  "Nashik Road / Railway Station": "Specify whether you mean the railway station or an address in the Nashik Road area. After a train arrival, agree an exit and a time that allows passengers to reach the car.",
  Panchavati: "If a Panchavati visit precedes departure, arrange the post-visit meeting point in advance. Temple or other visit timing should remain separate from the car's agreed waiting arrangement.",
  Deolali: "Give the Deolali property or host address and confirm any entry instructions. If collecting several relatives, list every pickup before deciding how the onward trip should be booked.",
  Gangavhare: "Use your Gangavhare host's exact meeting details. If the plan is a visit followed by travel elsewhere, establish whether the vehicle is retained or the booking ends at the first drop.",
  "Gangapur Dam / Sula Zone": "Choose the exact venue within the Gangapur Dam / Sula zone. A broad leisure-area name does not identify your stay, admission arrangements or where the driver should collect the group.",
  Satpur: "For a Satpur workplace visit, record the premises and gate details. If the finish time is uncertain, agree how the return pickup is arranged before deciding on a one-way drop.",
  "Trimbak Road": "Name the property on Trimbak Road where you will meet the car. Travel along a road bearing a destination name should not be confused with booking all the way to that destination.",
  "Gangapur Road": "Share the building or accommodation name on Gangapur Road. If the journey includes a leisure visit elsewhere, specify its address rather than treating the pickup corridor as the full itinerary.",
  "College Road": "For College Road, agree a venue entrance and passenger-ready time. A pickup after an appointment should allow your party to assemble before an onward intercity trip begins.",
  "Mumbai Naka": "Use a specific meeting landmark or property at Mumbai Naka. The name is a pickup-zone reference; the destination still needs to be selected independently in the journey search.",
  "Govind Nagar": "For a Govind Nagar residential or hotel pickup, provide the full building address. Settle any luggage collection at another location before requesting the final onward journey.",
  "Central Bus Stand": "Confirm the city and particular Central Bus Stand meeting point. Bus arrival and cab departure are separate events; choose a pickup time when the passengers can be at the agreed location.",
  CIDCO: "Provide the complete CIDCO address within Sambhajinagar. If meeting after a work or family visit, identify the entrance and distinguish a city pickup from an onward heritage circuit.",
  "Bansilal Nagar / Railway Station": "Choose between a Bansilal Nagar property and a station arrival. For the latter, agree an exit; for the former, use the host's street address and property entrance.",
  "Jalna Road": "State the actual premises on Jalna Road rather than using the road name alone. A pickup there does not imply a trip to Jalna; choose the intended destination separately.",
  "Airport Road": "An Airport Road address is not necessarily a terminal pickup. Confirm the exact property and use flight-specific meeting details only when the ride actually begins at the airport.",
  Waluj: "If collecting from Waluj business premises, obtain gate or visitor instructions. A journey with additional worksite stops should list them before the car and service are selected.",
  "Kranti Chowk": "Choose an identifiable host address or meeting point around Kranti Chowk. Avoid assuming the driver can find the party from the junction name without an agreed location.",
  "Central Chhatrapati Sambhajinagar": "Narrow the central-city pickup to a building or accommodation address. If the next stage is Ajanta or Ellora, name the intended visit instead of using a general city tour description.",
  "MGM / Seven Hills": "Confirm the specific premises in the MGM / Seven Hills zone and the entrance your party will use. Any access or mobility needs should be discussed before selecting a vehicle.",
  "Town Center": "Use Town Center with the full Sambhajinagar address and venue name. If colleagues leave from different premises, establish the pickup order before comparing a local day with an outward transfer.",
  Chikalthana: "For a Chikalthana pickup, distinguish the property address from an airport meeting. Confirm the starting point with your host and keep flight or visitor instructions relevant to that exact location.",
  Usmanpura: "Share the Usmanpura building and entrance for pickup. If luggage is stored elsewhere while you attend an appointment, include that collection in the plan before the final drop.",
  "Samarth Nagar": "Agree one Samarth Nagar meeting address for the travelling group. Multiple households joining a journey should provide their collection sequence rather than relying on a single neighbourhood label.",
  "Central Bus Stand / Kotwalpura": "Specify a bus-stand meeting or a Kotwalpura street address. If arriving by bus, reconfirm where passengers will leave the terminal and when they can meet the cab.",
  "Railway Station Road": "Identify the property on Railway Station Road or explicitly request a station meeting. A road address does not tell the driver which train exit passengers intend to use.",
  "Beed Bypass": "Provide the venue or property address on Beed Bypass. The pickup corridor name does not determine the final destination, so choose Beed only if that is where the trip actually ends.",
  Somalwada: "For a Somalwada pickup, use the building or stay address and agree when bags are ready. A later airport or intercity connection should be stated as the destination, not inferred from the pickup zone.",
  "Wardha Road": "Use the precise premises on Wardha Road in Nagpur. A road-name pickup and a trip to Wardha are separate choices; make the intended final drop clear in the search.",
  Sitabuldi: "Agree the exact Sitabuldi venue or meeting location. If your day includes several city appointments before departure, list them and consider a local package for that separate part of the plan.",
  "Central Avenue": "Provide the property name and entrance on Central Avenue. If members of the party meet from different places, set a collection order instead of treating the whole road as one pickup.",
  "Ganesh Peth Colony": "For Ganesh Peth Colony, distinguish a local address from a transport connection. Share the actual host or meeting point and choose pickup after the passengers are ready.",
  "Mohan Nagar": "Use the full Mohan Nagar address and a clear entrance description. If a station connection is intended, state that separately so the driver knows whether to meet at the property or the terminal.",
  "Sonegaon / Airport": "Specify a Sonegaon address or an airport meeting rather than relying on the combined zone name. For a flight-related pickup, confirm the passenger meeting instructions independently.",
  Dhantoli: "For a Dhantoli appointment pickup, agree an entrance that works for the passengers. Discuss any access or assistance needs and set the time after the appointment has finished.",
  Ramdaspeth: "Share the Ramdaspeth venue and a passenger-ready time. If someone needs to collect luggage or another traveller before leaving Nagpur, include that stop in the request.",
  Khamla: "Use a specific Khamla property address and establish where the group gathers. A neighbourhood pickup should remain distinct from any airport transfer details associated with the onward journey.",
  "Civil Lines": "For Civil Lines in Nagpur, name the office, accommodation or host premises. Ask for visitor access instructions if applicable and decide whether later meetings require retaining the car.",
  Sadar: "Choose the particular Sadar address rather than a general shopping or meeting area. If the party leaves after separate activities, agree a common collection point and departure time.",
  "Manish Nagar": "Give the Manish Nagar building entrance and any second pickup. Consider passengers and luggage together before choosing a vehicle category for an intercity departure.",
  "Nagpur Junction Railway Station": "Agree the Nagpur Junction exit or meeting point before the train arrives. Allow for reaching the car with luggage rather than setting cab pickup exactly at the scheduled train arrival.",
  "MIHAN / Airport Corridor": "Identify the particular MIHAN premises or the airport as the actual starting point. Worksite visitor instructions and flight-arrival instructions serve different pickups and should not be interchanged.",
  "Murarji Peth": "Use the Murarji Peth property and entrance for collection. If another passenger joins from Dharamsi Lane, list that address separately unless everyone is meeting at the same point.",
  Jule: "Provide the exact Jule address and the place your party will wait. An airport-related journey should name its airport endpoint explicitly instead of being inferred from the locality.",
  "Dharamsi Lane / Murarji Peth": "Specify Dharamsi Lane and the relevant building within the wider Murarji Peth zone. Confirm the practical meeting point with your host if the property entrance is not where vehicles should wait.",
  "Budhavar Peth": "Give the full Budhavar Peth host or property address. If the family group boards at more than one place, settle the order of collection before choosing the onward service.",
  "Old Police Line": "Use the current venue name and full address in the Old Police Line area. Avoid relying only on an area landmark when the driver needs to identify a particular entrance.",
  "Bhawani Peth": "For a Bhawani Peth pickup, agree a clear building or meeting-point name. If leaving for a pilgrimage, list all intended destination stops rather than just the first temple town.",
  "Railway Lines": "Railway Lines is the pickup-area name here; it is not automatically a railway-station meeting. Provide your actual address or explicitly specify the station and agreed exit.",
  "Sakhar Peth": "Identify the Sakhar Peth premises where passengers will assemble. For a trip after a visit or shopping, have the luggage and group ready before the chosen collection time.",
  "Mahesh Nagar": "Share a complete Mahesh Nagar address, including the property name. Any collection from another Solapur neighbourhood should be included in the trip instead of assumed within one pickup.",
  "Damani Nagar": "For Damani Nagar, agree the residence or venue entrance and departure time. If passengers return on a different day, enter that date when comparing a return journey.",
  "Navi Peth": "Use Navi Peth together with the Solapur property address. When relatives join from another locality, decide whether to gather at one place or request several named collections.",
  "Hotgi Road": "Give the actual property along Hotgi Road and its meeting instructions. A corridor name alone cannot identify the pickup, and any onward stop needs its own destination entry.",
  "Solapur Railway Station": "For Solapur Railway Station, confirm the passenger exit and readiness after arrival. Share enough time for luggage collection and meeting the driver before the onward road journey.",
  "Solapur Airport / Jule": "Choose the specific Jule address or airport endpoint within this combined zone. Verify flight arrangements separately; the guide does not assert a flight schedule or a dedicated airport service.",
  "Saat Rasta": "Agree a particular property or meeting landmark at Saat Rasta. A broad junction name should be narrowed down so passengers and driver have the same collection location.",
  Shahupuri: "Use the Shahupuri property address and distinguish it from a New Shahupuri pickup. If the journey follows checkout, choose the time when passengers and bags can be at the entrance.",
  "Tarabai Park": "For Tarabai Park, provide the hotel, host or venue entrance. If a later pilgrimage visit is planned, include its destination separately from the initial city collection.",
  Laxmipuri: "Agree an identifiable Laxmipuri meeting point with your host. For a group leaving after separate visits, establish one assembly time before requesting the onward car.",
  "Rajaram Road": "State the property name on Rajaram Road and confirm its entrance. Additional collection along the road is still a separate stop and should appear in the trip request.",
  "New Shahupuri": "Specify New Shahupuri and the actual building rather than only Shahupuri. If arriving from another mode of transport, distinguish its meeting point from your later accommodation pickup.",
  "Shivaji Peth A Ward": "Use the complete Shivaji Peth A Ward address and host's collection instructions. Discuss any practical passenger access needs before comparing the available vehicle categories.",
  "Mangalwar Peth": "For Mangalwar Peth, identify the residence or venue where passengers meet. If several family members are joining, settle the collection order and combined luggage before the intercity leg.",
  "Shahu Market Yard": "Choose the particular premises or agreed meeting point at Shahu Market Yard. If leaving after an appointment, schedule passenger collection independently of when the visit is expected to end.",
  "Laxminarayan Nagar": "Share the Laxminarayan Nagar property name and exact address. Decide whether everyone boards there or whether another city pickup must be added before the final destination.",
  Rankala: "For a Rankala visit, agree a specific road meeting point after the outing. If the car is retained, confirm waiting and the final drop rather than assuming the visit fits a direct transfer.",
  "Mahalaxmi Temple / Mahadwar Road": "Keep the temple visit separate from the vehicle meeting point on or near Mahadwar Road. Agree how the group contacts the driver after the visit without promising access or darshan timing.",
  "Kolhapur Bus Stand": "Confirm the particular Kolhapur Bus Stand arrival and passenger meeting point. Set the cab pickup for when the party can leave the terminal with luggage, allowing for the bus connection.",
  "Kolhapur Railway Station": "For a Kolhapur Railway Station arrival, agree an exit and meeting instructions. If another passenger joins from a hotel, name that collection before the intercity departure.",
  "Ujalaiwadi / Kolhapur Airport": "Specify an Ujalaiwadi property or Kolhapur Airport as the pickup. Flight-related meeting details are separate from a neighbourhood address and need to match the passenger's actual arrival.",
  Rajarampuri: "Give the Rajarampuri building and entrance for pickup. For a day with city visits before a return journey, list the stops and decide which part needs a local package.",
};
