export interface InfoSection { heading: string; paragraphs: string[] }
export interface InfoPage { slug: string; title: string; description: string; review: boolean; sections: InfoSection[] }
const section = (heading: string, ...paragraphs: string[]): InfoSection => ({ heading, paragraphs });
// BUSINESS / LEGAL REVIEW: Replace nulls only with approved business records.
// No address, email, registration, refund deadline or jurisdiction is inferred
// from legacy marketing copy or a vendor/customer record.
export const PUBLIC_BUSINESS_REVIEW = {
  legalEntityName: null, registeredAddress: null, registrationNumber: null, gstNumber: null,
  supportEmail: "service@wellcabs.com", supportPhone: "9011079304", privacyContact: null, grievanceProcess: null,
  retentionSchedule: null, refundProcessingTime: null, cancellationSchedule: null,
  applicableJurisdiction: null, effectiveDate: null, corporateAgreement: null,
};
const contact = section("Questions and requests", "Use verified contact details supplied with your booking or business agreement, where available. Do not share payment credentials or one-time passwords.", "Business review required: confirm and publish the responsible legal entity, service address, support channel and privacy/grievance contact before treating these notices as final.");
export const INFO_PAGES: InfoPage[] = [
  { slug: "privacy-policy", title: "Privacy Policy", description: "How RideGrid handles account, journey and payment-related information, and how to raise a privacy request.", review: true, sections: [
    section("Information and purposes", "Account information can include your name, contact details and authentication records. Journey information includes pickup and destination, travel date, selected service and booking reference. These records support account access, booking coordination and service administration."),
    section("Payments and location", "The booking flow uses a payment-provider integration. Payment references, amounts and transaction states may be retained for reconciliation and support. Enter payment credentials only in the payment provider's secure interface.", "Journey locations are used to search and coordinate a trip. If a location feature requests device permission, review the browser prompt; you can decline or change that permission in your device settings."),
    section("Cookies and service providers", "Authentication cookies and local browser storage support account sessions and essential application functions. The Cookie Policy explains these categories.", "Transport providers, payment services, infrastructure providers and authorized personnel may need relevant information to fulfil their roles. Business review must confirm the recipient list, purposes, contractual safeguards and any international processing."),
    section("Retention and security", "Keep information only for the confirmed operational, contractual and legal purposes for which it is required. The business must approve and document a retention and deletion schedule.", "Access controls and authentication help protect information. No website or transmission method can promise absolute security. Report a suspected account issue through a verified support channel."),
    section("Choices, rights and grievances", "Depending on applicable law and the processing involved, you may be able to request access, correction, erasure, consent withdrawal, grievance redressal or nomination. Identity verification may be necessary before a request can be handled.", "Business review required: publish the request method, responsible contact and escalation process. Explain any consequences of withdrawing consent, the treatment of children's data, and any applicable exceptions. A policy page alone does not establish DPDP compliance."),
    section("Policy changes", "Material changes should be communicated with an approved effective date and a clear explanation. The business must complete legal review against the applicable commencement provisions before final adoption."), contact,
  ] },
  { slug: "terms-and-conditions", title: "Terms & Conditions", description: "Read the framework for using RideGrid, choosing a journey and managing a booking.", review: true, sections: [
    section("Using RideGrid", "RideGrid by Wellcabs connects journey search, marketplace vehicle choices and booking administration. Provide accurate information and use the service only for lawful travel and authorized account activity."),
    section("Bookings, prices and payments", "A search result is not a completed booking. Review the selected vehicle, pickup details, fare breakdown, inclusions, exclusions and payment status in the current booking flow.", "Availability and quoted amounts can change before confirmation. Do not rely on historical marketing prices. Any accepted booking and applicable service-specific conditions should be retained for reference."),
    section("Transport providers and responsibilities", "The marketplace uses vehicle and vendor records to present transport options. The responsible provider and the platform's role must be clearly identified in the booking or governing agreement. This website does not imply that every listed vehicle is owned by RideGrid."),
    section("Cancellations and user obligations", "Cancellation eligibility and any refund depend on the terms accepted for the specific booking and applicable law. Refer to the Cancellation & Refund Policy and your booking record.", "Be ready at the agreed pickup point, provide correct passenger and journey details, follow lawful safety requirements and do not misuse accounts or interfere with vehicles, personnel or platform systems."),
    section("Prohibited use and intellectual property", "Do not attempt unauthorized access, fraud, harassment, scraping that disrupts service, or infringement of third-party rights. Platform names, designs and content remain subject to their respective intellectual property rights."),
    section("Availability and limitation framework", "Travel conditions, network interruptions and provider availability can affect service. Any limitation of responsibility must be specified in an approved agreement and remain subject to non-excludable consumer rights and applicable law. No blanket waiver is created by this draft."),
    section("Changes and disputes", "Business/legal review required: identify the contracting entity, effective date, applicable law, dispute process and any agreed jurisdiction. Do not infer these details from the location of a trip."), contact,
  ] },
  { slug: "cancellation-refund-policy", title: "Cancellation & Refund Policy", description: "Understand booking cancellation, refund review and payment status without relying on unverified timelines.", review: true, sections: [
    section("Before you cancel", "Review your confirmed booking and any cancellation terms shown when it was accepted. Eligibility can depend on the journey, provider and booking state. No universal free-cancellation window is stated here."),
    section("Requesting a cancellation", "Use a cancellation action in your booking account where one is available, or the verified contact supplied for your booking. Keep the booking reference and a record of the request. A request is not a completed cancellation until its status is confirmed."),
    section("Refund review", "A refund requires review of the amount paid, applicable deductions and any prior refunds. Payment status and refund status are distinct. A cancellation does not automatically establish a refund amount."),
    section("Timing and exceptions", "Business review required: publish the approved cancellation schedule, no-show treatment, partial-use rules, dispute path and refund processing timeframe. Bank and payment-provider processing can be separate from internal approval. No unverified number of days is promised."), contact,
  ] },
  { slug: "cookie-policy", title: "Cookie Policy", description: "Information about essential cookies, session storage and browser controls on RideGrid.", review: true, sections: [
    section("Essential browser storage", "RideGrid uses authentication cookies, including ridegrid_access_token and ridegrid_refresh_token, to support account sessions. Browser storage may retain account-interface state. These are separate from the journey details held in the booking system."),
    section("Other technologies", "The business must maintain a verified inventory of analytics, advertising and third-party storage before enabling those technologies. This notice does not assert that optional tracking is present, nor does it provide consent for tracking that has not been disclosed."),
    section("Your controls", "You can inspect, block or clear cookies and site storage in browser settings. Blocking essential storage may prevent login or interrupt account functions. Device location permission is controlled separately by your browser or operating system."), contact,
  ] },
  { slug: "disclaimer", title: "Disclaimer", description: "How to interpret travel information, marketplace availability and illustrative imagery on RideGrid.", review: true, sections: [
    section("Travel information", "Editorial pages help you plan. They are not a guarantee of travel time, road conditions, availability or a particular vehicle. Check the current journey and booking details before paying."),
    section("Images and third-party material", "Website visuals may be illustrative, including reviewed AI-generated images. An illustration is not proof of an owned fleet, an actual passenger journey or a specific available vehicle. Marketplace listing details take precedence for the selected option."),
    section("Your rights", "Nothing on this page is intended to exclude rights that cannot lawfully be excluded. Business/legal review must confirm the contracting entity and any service-specific limitations."), contact,
  ] },
  { slug: "accessibility", title: "Accessibility Statement", description: "Keyboard navigation, readable content and ways to report accessibility barriers on RideGrid.", review: false, sections: [
    section("Using this website", "The public website includes semantic headings, labeled search controls, visible keyboard focus, a skip-to-content link and reduced-motion support. Use browser zoom to adjust text size."),
    section("Ongoing improvements", "Accessibility is an ongoing process. This statement does not claim certification or complete conformance. Third-party payment and location interfaces may behave differently from the public website."),
    section("Reporting a barrier", "If a verified booking contact is available, describe the page, device and barrier without including sensitive payment details. Business review required: publish a dedicated accessibility contact and response process."),
  ] },
  { slug: "about", title: "About Wellcabs", description: "Your journey, your choice. Wellcabs brings cab search, vehicle choices and booking into one connected travel experience.", review: false, sections: [
    section("Ground travel, thoughtfully connected", "RideGrid by Wellcabs brings together journey search, available marketplace options and a managed booking flow. Start with your travel plans, compare the current choices and review the details before you book."),
    section("Every journey starts with clarity", "Explore one-way, round-trip, local, airport and rental options where they are available in the live marketplace. Business travel uses the platform's corporate account and approval workflow where enabled."),
    section("Built around real information", "Published travel pages and managed visuals complement the live marketplace. We do not substitute invented fares, reviews or counts for actual availability."),
  ] },
  { slug: "contact", title: "Contact Wellcabs", description: "Contact Wellcabs for cab booking help and business enquiries. Call 9011079304, message us on WhatsApp or email service@wellcabs.com.", review: false, sections: [
    section("Existing bookings", "Keep your booking reference, travel date and payment reference ready. If your booking confirmation or agreement provides a verified contact, use that channel. Never share passwords, card security codes or one-time passwords."),
    section("Booking and payment questions", "You can return to the marketplace to review current journey options. For a payment query, retain the provider reference and check the recorded payment status before attempting a second payment."),
    section("Booking and business enquiries", "Call 9011079304 or email service@wellcabs.com for booking help and business enquiries. Our office is at L-307, 2nd floor, Mega Center, Pune - Solapur Rd, Magarpatta, North Hadapsar, Hadapsar, Pune, Maharashtra 411028."),
  ] },
  { slug: "payment-refund-information", title: "Payment & Refund Information", description: "Practical information about RideGrid payment references, confirmation and refund review.", review: true, sections: [
    section("Paying for a booking", "Review the amount and breakdown in the existing booking flow. Available payment methods are those presented for that booking. Complete any required verification in the payment provider's interface."),
    section("Confirmation and duplicate payments", "A successful browser redirect alone is not proof of a confirmed payment. Check the booking and payment records. If the result is unclear, keep the payment reference and verify the status before trying again."),
    section("Refund information", "Refunds are assessed against the booking's accepted terms, payment history and any prior refunds. See the Cancellation & Refund Policy. Business review must approve the processing timeframe and escalation contact before publication as binding terms."), contact,
  ] },
  { slug: "business-travel-terms", title: "Business Travel Terms", description: "A framework for corporate account access, approvals and business travel arrangements.", review: true, sections: [
    section("Corporate travel arrangements", "Corporate accounts can involve authorized administrators, employee travel and approval controls. Access and responsibilities depend on the account setup and the signed business agreement."),
    section("Approvals, billing and credit", "Do not assume that a booking is approved or that credit is available until the account workflow confirms it. Billing, credit limits, payment terms and cancellation obligations must follow the verified corporate agreement."),
    section("Business review required", "Confirm the contracting parties, authorized users, service scope, billing arrangements, data-sharing terms and dispute process. No commercial credit, discount or service-level guarantee is offered by this draft page."), contact,
  ] },
];
export const LEGAL_LINKS = INFO_PAGES.filter(p => !["about", "contact"].includes(p.slug)).map(p => ({ label: p.title, href: `/${p.slug}` }));
