"use client";

import { useEffect, useState } from "react";
import RealEntitySync from "./RealEntitySync";
import Link from "next/link";
import { factoryApi } from "@/lib/website-seo/page-factory/client";
import { FACTORY_TYPES } from "@/lib/website-seo/page-factory/config";
import { ROLLOUTS } from "@/lib/website-seo/scale/logic";
import type { Inspection } from "@/lib/website-seo/scale/candidates";
import type { overview, quality } from "@/lib/website-seo/scale/reporting";
import type { runDetail, existingCandidates } from "@/lib/website-seo/scale/service";
import { FactoryHeading, Feedback, buttonClass, primaryClass, inputClass, Handoff } from "./shared";

type Overview = Awaited<ReturnType<typeof overview>>;
type Detail = Awaited<ReturnType<typeof runDetail>>;
type Existing = Awaited<ReturnType<typeof existingCandidates>>;
type Quality = Awaited<ReturnType<typeof quality>>;
type Runs = { items: { id: string; name: string; entityType: string; status: string; rolloutLevel: string; _count: { items: number } }[]; nextCursor: string | null };
const tabs = ["Overview", "Plan", "Candidates", "Runs", "Quality", "Coverage"] as const;
const card = "rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm";

export default function ScaleControlClient() {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Overview");
  const [summary, setSummary] = useState<Overview | null>(null), [runs, setRuns] = useState<Runs | null>(null);
  const [detail, setDetail] = useState<Detail | null>(null), [existing, setExisting] = useState<Existing | null>(null), [checks, setChecks] = useState<Quality | null>(null);
  const [name, setName] = useState(""), [type, setType] = useState("ROUTE"), [level, setLevel] = useState("PILOT_10"), [limit, setLimit] = useState(10), [batch, setBatch] = useState(10);
  const [text, setText] = useState(""), [inspection, setInspection] = useState<Inspection[]>([]);
  const [picked, setPicked] = useState<string[]>([]), [existingPicked, setExistingPicked] = useState<string[]>([]);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [filter, setFilter] = useState("");
  const runId = detail?.run.id;
  async function task(fn: () => Promise<void>) { setBusy(true); setError(""); setNotice(""); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : "Request failed."); } finally { setBusy(false); } }
  async function loadRuns(cursor?: string) { setRuns(await factoryApi<Runs>(`scale/runs${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ""}`)); }
  async function loadDetail(id: string, cursor?: string, status = filter) {
    const q = new URLSearchParams({ ...(cursor ? { cursor } : {}), ...(status ? { status } : {}) });
    setDetail(await factoryApi<Detail>(`scale/runs/${id}?${q}`)); setPicked([]);
  }
  useEffect(() => { void task(async () => { const data = await factoryApi<Overview>("scale/overview"); setSummary(data); await loadRuns(); }); }, []);
  const toggle = (values: string[], id: string) => values.includes(id) ? values.filter(v => v !== id) : [...values, id];
  const refresh = () => task(async () => { setSummary(await factoryApi<Overview>("scale/overview")); await loadRuns(); if (runId) await loadDetail(runId); });
  const coverage = <div className={`${card} overflow-x-auto`}><h2 className="text-lg font-black">Entity coverage</h2><p className="my-3 text-sm text-zinc-600">{summary?.definitions}</p><table className="w-full text-left text-sm"><thead><tr>{["Family", "Entities", "Pages", "Published", "W3 ready", "Stored quality blocked", "Keywords", "Content", "SEO", "Entity coverage"].map(h => <th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{summary?.coverage.map(r => <tr key={r.entityType} className="border-t border-zinc-100">{[r.entityType, r.entities, r.pages, r.published, r.ready, r.blocked, r.keywords, r.content, r.seo, r.coveragePercent === null ? "—" : `${r.coveragePercent}%`].map((v, i) => <td key={i} className="p-2">{v}</td>)}</tr>)}</tbody></table>{!summary && <p className="py-4">Coverage has not loaded.</p>}</div>;
  return <>
    <FactoryHeading title="Scale Control Center" description="Pilot 10 → review → 100 → review → 1,000. Build useful pages from real entities, with quality and publication review at every stage." action={<button disabled={busy} className={buttonClass} onClick={refresh}>Refresh</button>} />
    <main className="mx-auto max-w-7xl space-y-5 px-6 py-6 lg:px-8">
      <Feedback error={error} notice={busy ? "Working on the requested operation…" : notice} />
      <nav aria-label="Scale sections" className="flex gap-2 overflow-x-auto">{tabs.map(t => <button key={t} aria-current={tab === t ? "page" : undefined} className={tab === t ? primaryClass : buttonClass} onClick={() => setTab(t)}>{t}</button>)}</nav>
      {tab === "Overview" && <>
        <RealEntitySync onSync={() => { void refresh(); }} />
        <div className={card}><h2 className="text-lg font-black">Scale readiness</h2><p className="mt-2">Generation stops at W7 readiness. Publication requires a separate governed action.</p>{summary && <div className="mt-3 space-y-2 text-sm"><p>{summary.governance.publicationLabel}</p><p>W12 approval: {summary.governance.automationMode} · W13 approval: {summary.governance.aiMode} · Effective batch cap: {summary.governance.batchLimit}</p><p>W13 generation: {summary.governance.generationAllowed ? "Allowed for manually requested batches" : "Blocked by generation rules"}</p><p>Search-volume and opportunity metrics: unavailable.</p></div>}<div className="mt-4 flex flex-wrap gap-3"><button className={primaryClass} onClick={() => setTab("Plan")}>Create a pilot plan</button><Link className={buttonClass} href="/website-seo/automation">Automation governance</Link><Link className={buttonClass} href="/website-seo/ai-control">AI governance</Link></div></div>{coverage}
      </>}
      {tab === "Plan" && <div className={card}><h2 className="text-lg font-black">New scale plan</h2><p className="mt-2 text-sm text-zinc-600">Start with 10 and review blocked pages before increasing scope. Maximum 5,000 candidates per plan; import up to 100 at a time.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <label className="text-sm font-bold">Plan name<input className={inputClass} value={name} maxLength={120} onChange={e => setName(e.target.value)} /></label>
        <label className="text-sm font-bold">Entity family<select className={inputClass} value={type} onChange={e => { setType(e.target.value); setExisting(null); setExistingPicked([]); }}>{FACTORY_TYPES.map(t => <option key={t.type} value={t.type}>{t.label}</option>)}</select></label>
        <label className="text-sm font-bold">Rollout<select className={inputClass} value={level} onChange={e => setLevel(e.target.value)}>{Object.entries(ROLLOUTS).map(([k, v]) => <option key={k} value={k}>{k === "CUSTOM" ? "Custom (maximum 5,000)" : `${k} · ${v}`}</option>)}</select></label>
        {level === "CUSTOM" && <label className="text-sm font-bold">Custom limit<input type="number" min={1} max={5000} value={limit} className={inputClass} onChange={e => setLimit(Number(e.target.value))} /></label>}
        <label className="text-sm font-bold">Batch size<input type="number" min={1} max={25} value={batch} className={inputClass} onChange={e => setBatch(Number(e.target.value))} /></label>
      </div><button disabled={busy || !name.trim()} className={`${primaryClass} mt-5`} onClick={() => task(async () => { const r = await factoryApi<{ id: string }>("scale/plan", { name, entityType: type, rolloutLevel: level, itemLimit: limit, batchSize: batch }); await loadDetail(r.id); setInspection([]); setExisting(null); setExistingPicked([]); setTab("Candidates"); await loadRuns(); })}>Create draft plan</button></div>}
      {tab === "Candidates" && <>
        {!detail ? <div className={card}>Create a plan or open one from Runs to import and select candidates.</div> : <>
          <div className={card}><h2 className="text-lg font-black">{detail.run.name} · {detail.run.entityType}</h2><p className="mt-2 text-sm">{detail.run.candidateCount} / {detail.run.itemLimit} candidates · {detail.run.total} selected · {detail.run.status}</p><p className="mt-2 text-sm text-zinc-600">New entities remain W2 drafts. Add verified metadata and complete editorial review through the existing engines.</p>
          {detail.run.status === "DRAFT" && <><label className="mt-4 block text-sm font-bold">Paste JSON array or CSV (type,name,slug,metadata)<textarea rows={7} className={`${inputClass} font-mono`} value={text} onChange={e => { setText(e.target.value); setInspection([]); }} /></label><label className="mt-3 block text-sm">Import a .csv or .json file<input type="file" accept=".csv,.json" className="ml-3" onChange={e => { const file = e.target.files?.[0]; if (file) void task(async () => { if (file.size > 1_000_000) throw new Error("File exceeds 1 MB."); setText(await file.text()); setInspection([]); }); }} /></label><div className="mt-3 flex gap-3"><button disabled={busy || !text.trim()} className={buttonClass} onClick={() => task(async () => { setInspection(await factoryApi<Inspection[]>("scale/candidates", { action: "dryRun", runId, text })); })}>Dry run (read only)</button><button disabled={busy || !inspection.length || inspection.some(r => ["INVALID", "CONFLICT"].includes(r.classification))} className={primaryClass} onClick={() => task(async () => { await factoryApi("scale/candidates", { action: "import", runId, text }); setText(""); setInspection([]); await loadDetail(runId!); setNotice("Candidates imported. Inspect and explicitly select eligible items."); })}>Import validated candidates</button></div>
          <div className="mt-5 border-t pt-4"><button disabled={busy} className={buttonClass} onClick={() => task(async () => { setExisting(await factoryApi<Existing>(`scale/candidates?type=${detail.run.entityType}`)); setExistingPicked([]); })}>Choose existing W2 entities</button>{existing && <div className="mt-3 space-y-2">{!existing.items.length && <p>No existing entities in this family.</p>}{existing.items.map(e => <label key={e.id} className="flex gap-2 text-sm"><input type="checkbox" checked={existingPicked.includes(e.id)} onChange={() => setExistingPicked(toggle(existingPicked, e.id))} />{e.name} · {e.slug} · {e.status}</label>)}<div className="flex gap-3"><button disabled={busy || !existingPicked.length} className={primaryClass} onClick={() => task(async () => { await factoryApi("scale/candidates", { action: "existing", runId, ids: existingPicked }); setExistingPicked([]); await loadDetail(runId!); })}>Import chosen entities</button>{existing.nextCursor && <button disabled={busy} className={buttonClass} onClick={() => task(async () => { setExisting(await factoryApi<Existing>(`scale/candidates?type=${detail.run.entityType}&cursor=${existing.nextCursor}`)); setExistingPicked([]); })}>Next entities</button>}</div></div>}</div></>}
          </div>
          <div className={card}><h3 className="font-black">Saved candidates (50 per page)</h3>{!detail.items.length && <p className="mt-3 text-sm">No candidates yet. Import real entity data to begin.</p>}{detail.items.map(i => <label key={i.id} className="mt-3 flex items-start gap-3 border-t pt-3 text-sm"><input type="checkbox" checked={picked.includes(i.id)} onChange={() => setPicked(toggle(picked, i.id))} /><span>{i.name} · {i.slug}<br />{i.status} · {i.selected ? "Selected" : "Not selected"}{i.error && <span className="block text-red-700">{i.error}</span>}</span></label>)}<div className="mt-4 flex flex-wrap gap-3"><button disabled={busy || !picked.length} className={buttonClass} onClick={() => task(async () => { setInspection(await factoryApi<Inspection[]>("scale/candidates", { action: "inspectSaved", runId, ids: picked })); })}>Inspect checked</button>{detail.run.status === "DRAFT" && <>{[true, false].map(selected => <button key={String(selected)} disabled={busy || !picked.length} className={buttonClass} onClick={() => task(async () => { await factoryApi(`scale/runs/${runId}`, { action: "select", ids: picked, selected }); await loadDetail(runId!); })}>{selected ? "Approve checked for generation" : "Deselect checked"}</button>)}<button disabled={busy || !detail.run.total} className={primaryClass} onClick={() => task(async () => { setDetail(await factoryApi<Detail>(`scale/runs/${runId}`, { action: "ready" })); setTab("Runs"); await loadRuns(); })}>Mark plan ready</button></>}{detail.nextCursor && <button disabled={busy} className={buttonClass} onClick={() => task(() => loadDetail(runId!, detail.nextCursor!))}>Next candidates</button>}<button disabled={busy} className={buttonClass} onClick={() => task(() => loadDetail(runId!))}>First page</button></div></div>
        </>}
        {!!inspection.length && <div className={`${card} overflow-x-auto`}><h3 className="font-black">Dry-run results</h3><table className="mt-3 w-full text-left text-sm"><thead><tr>{["Candidate", "Classification", "Template", "Existing entity/page", "Path", "Keyword intent", "Eligibility"].map(h => <th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{inspection.map((r, i) => <tr key={i} className="border-t"><td className="p-2">{r.candidate?.name ?? "Invalid input"}</td><td>{r.classification}</td><td>{r.templateId ? "ACTIVE" : "Unavailable/ambiguous"}</td><td>{r.entityId ? "Entity exists" : "New entity"} / {r.pageId ? "Page exists" : "No page"}</td><td>{r.path ?? "—"}</td><td>{r.cannibalization}</td><td>{r.eligible ? "Eligible" : r.reasons.join(" ")}</td></tr>)}</tbody></table></div>}
      </>}
      {tab === "Runs" && <>
        <div className={card}><h2 className="text-lg font-black">Plans and runs</h2>{!runs?.items.length && <p className="mt-3">No plans yet. Start with a pilot of 10.</p>}{runs?.items.map(r => <button key={r.id} disabled={busy} className="mt-3 block w-full rounded-xl border p-3 text-left text-sm hover:border-red-400" onClick={() => task(async () => { setFilter(""); await loadDetail(r.id, undefined, ""); setInspection([]); setExisting(null); })}>{r.name} · {r.entityType} · {r.rolloutLevel} · {r.status} · {r._count.items} candidates</button>)}<div className="mt-3 flex gap-3"><button disabled={busy} className={buttonClass} onClick={() => task(() => loadRuns())}>Latest plans</button>{runs?.nextCursor && <button disabled={busy} className={buttonClass} onClick={() => task(() => loadRuns(runs.nextCursor!))}>Older plans</button>}</div></div>
        {detail && <div className={card}><h3 className="text-lg font-black">{detail.run.name} · {detail.run.status}</h3><p className="mt-3">{detail.run.processed} / {detail.run.total} processed · {detail.run.completed} passed W7 · {detail.run.blocked} blocked · {detail.run.failed} failed</p><progress className="mt-3 h-3 w-full accent-red-600" value={detail.run.percent} max={100} aria-label="Run progress" /><p className="mt-2 text-sm">{detail.run.percent}% processed. Completion includes blocked items; review quality before expanding.</p>{detail.run.executing && <p className="mt-2 text-sm">A worker owns this run. Pause takes effect after the current item. If its process terminated, use the documented recovery procedure.</p>}<div className="mt-4 flex flex-wrap gap-3"><button disabled={busy} className={buttonClass} onClick={() => setTab("Candidates")}>Manage candidates</button><button disabled={busy || detail.run.executing || !["READY", "RUNNING"].includes(detail.run.status)} className={primaryClass} onClick={() => task(async () => { setDetail(await factoryApi<Detail>(`scale/runs/${runId}/execute`, {})); await loadRuns(); })}>Execute next batch (≤ {Math.min(detail.run.batchSize, summary?.governance.batchLimit ?? 25)})</button>{["READY", "RUNNING", "PAUSED"].includes(detail.run.status) && <button disabled={detail.run.status === "PAUSED" && (busy || detail.run.executing)} className={buttonClass} onClick={() => { const action = detail.run.status === "PAUSED" ? "resume" : "pause"; void factoryApi<Detail>(`scale/runs/${runId}`, { action }).then(setDetail).catch(e => setError(String(e))); }}>{detail.run.status === "PAUSED" ? "Resume" : "Pause"}</button>}<button disabled={busy} className={buttonClass} onClick={() => task(() => loadDetail(runId!))}>Refresh run</button></div><label className="mt-5 block text-sm font-bold">Item status<select className={inputClass} value={filter} onChange={e => { setFilter(e.target.value); void task(() => loadDetail(runId!, undefined, e.target.value)); }}>{["", "READY", "COMPLETED", "BLOCKED", "FAILED"].map(s => <option key={s} value={s}>{s || "All"}</option>)}</select></label>{detail.items.map(i => <p key={i.id} className="mt-3 border-t pt-3 text-sm">{i.name} · {i.status}{i.error ? ` — ${i.error}` : ""}</p>)}{detail.nextCursor && <button className={`${buttonClass} mt-3`} disabled={busy} onClick={() => task(() => loadDetail(runId!, detail.nextCursor!))}>Next items</button>}</div>}
      </>}
      {tab === "Quality" && <div className={card}><h2 className="text-lg font-black">Live W7 readiness</h2><p className="my-3 text-sm">Review 25 real pages per request. W5/W6 quality and W7 readiness remain authoritative. No generation or publication is performed here.</p><button disabled={busy} className={buttonClass} onClick={() => task(async () => setChecks(await factoryApi<Quality>("scale/quality")))}>Check first 25 pages</button>{checks && <><p className="mt-3 text-sm">Checked {checks.checkedAt}</p>{!checks.items.length && <p className="mt-3">No generated pages yet.</p>}{checks.items.map(p => <div key={p.id} className="mt-3 border-t pt-3 text-sm"><p className="font-bold">{p.pathname} · {p.ready ? summary?.governance.publicationLabel ?? "READY FOR PUBLICATION" : "BLOCKED"}</p>{p.reasons.map((r, i) => <p key={i}>{r}</p>)}</div>)}{checks.nextCursor && <button disabled={busy} className={`${buttonClass} mt-3`} onClick={() => task(async () => setChecks(await factoryApi<Quality>(`scale/quality?cursor=${checks.nextCursor}`)))}>Check next 25</button>}</>}<div className="mt-5"><Handoff /></div></div>}
      {tab === "Coverage" && coverage}
    </main>
  </>;
}
