// @vitest-environment node
import { beforeEach, describe, expect, it, vi } from "vitest";
import { Prisma } from "@prisma/client";
const db=vi.hoisted(()=>({ $queryRaw:vi.fn(), $transaction:vi.fn(), pricingRateVersion:{findUniqueOrThrow:vi.fn(),findUnique:vi.fn(),findFirst:vi.fn(),findMany:vi.fn(),create:vi.fn(),update:vi.fn()}, pricingRule:{findUniqueOrThrow:vi.fn()}, pricingPolicy:{findMany:vi.fn()}, pricingPackage:{findFirst:vi.fn()}, pricingQuote:{findUnique:vi.fn(),findMany:vi.fn(),create:vi.fn()}, vehicle:{findFirst:vi.fn()}, smartReturnListing:{findUnique:vi.fn()}, auditLog:{create:vi.fn()} }));
vi.mock("@/lib/prisma",()=>({prisma:db}));
import { transitionRate, createRate } from "@/lib/services/pricing/RateService";
import { assertQuoteUsable, consumeQuote, quoteService } from "@/lib/services/pricing/QuoteService";

const terms={method:"FIXED",includedKm:"0",includedHours:"0",minimumKmPerDay:"0",perKm:"0",perHour:"0",driverAllowance:"0",waitingPerHour:"0",nightCharge:"0",cancellationReference:"policy"};
const rate={id:"r",pricingRuleId:"card",pricingPackageId:null,vendorId:"vendor",vehicleCategory:"SEDAN",service:"OUTSTATION_ONE_WAY",city:"",origin:"",destination:"",area:"",scopeKey:"scope",version:2,status:"PENDING",effectiveFrom:new Date("2030-01-01"),effectiveTo:null,fare:new Prisma.Decimal(1000),smartReturnFare:null,terms};
const band={id:"band",key:"band",version:1,kind:"BAND",city:"",service:"",vehicleCategory:"",vendorId:"",route:"",active:true,effectiveFrom:new Date("2020-01-01"),effectiveTo:null,data:{minimum:"800",recommended:"1000",maximum:"1200",autoMinimum:"900",autoMaximum:"1100",smartMinimum:"600",smartMaximum:"900"}};
const admin={id:"admin",admin:true,finance:false}, vendor={id:"user-v",admin:false,finance:false,vendorId:"vendor"};
const request={vendorId:"vendor",vehicleId:"vehicle",vehicleCategory:"SEDAN",service:"OUTSTATION_ONE_WAY",at:new Date("2030-01-02T10:00:00Z"),ownerId:"customer",idempotencyKey:"key"};
beforeEach(()=>{vi.resetAllMocks();db.$transaction.mockImplementation(fn=>fn(db));db.pricingRateVersion.findUniqueOrThrow.mockResolvedValue(rate);db.pricingRateVersion.findMany.mockResolvedValue([]);db.pricingRateVersion.update.mockImplementation(async({data})=>({...rate,...data}));db.pricingPolicy.findMany.mockResolvedValue([band]);db.pricingQuote.findUnique.mockResolvedValue(null);db.pricingQuote.findMany.mockResolvedValue([]);db.vehicle.findFirst.mockResolvedValue({id:"vehicle",category:"SEDAN",vendorId:"vendor"});db.pricingQuote.create.mockImplementation(async({data})=>({id:"quote",...data}));});
describe("approval and rate version workflow",()=>{
  it("prevents cross-vendor approval and edits",async()=>{await expect(transitionRate({...vendor,vendorId:"other"},"r","submit","",2)).rejects.toThrow("own fares");expect(db.pricingRateVersion.update).not.toHaveBeenCalled();});
  it("requires Super Admin for manual approval",async()=>{await expect(transitionRate(vendor,"r","approve","approved",2)).rejects.toThrow("not permitted");});
  it("automatically approves submitted fares within the auto band",async()=>{db.pricingRateVersion.findUniqueOrThrow.mockResolvedValue({...rate,status:"DRAFT"});const result=await transitionRate(vendor,"r","submit","",2);expect(result.status).toBe("APPROVED");expect(db.auditLog.create).toHaveBeenCalledTimes(1);});
  it("requires a reason for an outside-band approval",async()=>{db.pricingRateVersion.findUniqueOrThrow.mockResolvedValue({...rate,fare:new Prisma.Decimal(1500)});await expect(transitionRate(admin,"r","approve","",2)).rejects.toThrow("reason");await expect(transitionRate(admin,"r","approve","Verified special event",2)).resolves.toMatchObject({status:"APPROVED"});});
  it("rejects stale expected versions",async()=>{await expect(transitionRate(admin,"r","approve","",1)).rejects.toThrow("VERSION_CONFLICT");});
  it("requires a rejection reason and writes audit atomically",async()=>{await expect(transitionRate(admin,"r","reject","",2)).rejects.toThrow();await transitionRate(admin,"r","reject","Rate needs review",2);expect(db.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({oldValue:expect.objectContaining({status:"PENDING"}),newValue:expect.objectContaining({status:"REJECTED"})})}));});
  it("prevents duplicate approved intervals with the same start",async()=>{db.pricingRateVersion.findMany.mockResolvedValue([{...rate,id:"old",status:"APPROVED"}]);await expect(transitionRate(admin,"r","approve","",2)).rejects.toThrow("future Effective From");});
  it("closes an older version atomically at a future boundary",async()=>{db.pricingRateVersion.findMany.mockResolvedValue([{...rate,id:"old",effectiveFrom:new Date("2029-01-01"),status:"APPROVED"}]);await transitionRate(admin,"r","approve","",2);expect(db.pricingRateVersion.update).toHaveBeenCalledWith({where:{id:"old"},data:{effectiveTo:rate.effectiveFrom}});expect(db.auditLog.create).toHaveBeenCalledTimes(2);});
  it("does not swallow audit failures",async()=>{db.auditLog.create.mockRejectedValue(new Error("audit unavailable"));await expect(transitionRate(admin,"r","approve","",2)).rejects.toThrow("audit unavailable");});
  it("requires an approved Smart Return band",async()=>{db.pricingRateVersion.findUniqueOrThrow.mockResolvedValue({...rate,smartReturnFare:new Prisma.Decimal(500)});await expect(transitionRate(admin,"r","approve","special",2)).rejects.toThrow("approved one-way band");});
  it("creates a new version instead of overwriting terms",async()=>{db.pricingRule.findUniqueOrThrow.mockResolvedValue({id:"card",vendorId:"vendor",vehicleCategory:"SEDAN"});db.pricingRateVersion.findFirst.mockResolvedValue(rate);db.pricingPolicy.findMany.mockResolvedValue([band,{...band,id:"master",kind:"MASTER",data:terms}]);db.pricingRateVersion.create.mockImplementation(async({data})=>({id:"new",...data}));const result=await createRate(vendor,{pricingRuleId:"card",service:"OUTSTATION_ONE_WAY",fare:"1010",effectiveFrom:"2031-01-01",expectedVersion:2});expect(result.version).toBe(3);expect(db.pricingRateVersion.update).not.toHaveBeenCalled();});
});
function quotePolicies(){return [{...band,kind:"FEE",id:"fee",data:{fixed:"50",percent:"0",minimum:"0",processingFixed:"0",processingPercent:"0",waive:false}},{...band,kind:"TAX",id:"tax",data:[]},{...band,kind:"CHARGES",id:"charges",data:[]},band];}
describe("authoritative quote lifecycle",()=>{
  beforeEach(()=>{db.pricingRateVersion.findMany.mockResolvedValue([{...rate,status:"APPROVED"}]);db.pricingPolicy.findMany.mockResolvedValue(quotePolicies());});
  it("rejects quotes at the exact expiry boundary",()=>{const at=new Date();expect(()=>assertQuoteUsable({expiresAt:at,ownerId:"u",vehicleId:"v"},"u","v",at)).toThrow("expired");});
  it("rejects another owner's quote",()=>expect(()=>assertQuoteUsable({expiresAt:new Date("2031-01-01"),ownerId:"other",vehicleId:"v"},"u","v")).toThrow("belong"));
  it("persists an immutable versioned breakdown",async()=>{const q=await quoteService.quote(request);expect(q.snapshot).toMatchObject({vendorFare:"1000.00",platformFee:"50.00",finalPayable:"1050.00",vendorPayout:"1000.00",rideGridRevenue:"50.00",rateVersion:2,rateCardId:"card",currency:"INR"});expect(db.pricingQuote.create).toHaveBeenCalledOnce();});
  it("returns the same snapshot for an idempotent retry",async()=>{const q=await quoteService.quote(request);const saved=db.pricingQuote.create.mock.calls[0][0].data;db.pricingQuote.findUnique.mockResolvedValue({...saved,id:q.id});const second=await quoteService.quote(request);expect(second).toEqual(q);expect(db.pricingQuote.create).toHaveBeenCalledOnce();});
  it("rejects idempotency-key reuse for a different trip",async()=>{await quoteService.quote(request);db.pricingQuote.findUnique.mockResolvedValue({...db.pricingQuote.create.mock.calls[0][0].data,id:"quote"});await expect(quoteService.quote({...request,at:new Date("2030-01-03")})).rejects.toThrow("IDEMPOTENCY_CONFLICT");});
  it("cannot issue an unconfigured tax quote",async()=>{db.pricingPolicy.findMany.mockResolvedValue(quotePolicies().filter(p=>p.kind!=="TAX"));await expect(quoteService.quote(request)).rejects.toThrow("TAX configuration");});
  it("quotes simplified roundtrip days with server Decimal pricing and central fees", async () => {
    db.pricingRateVersion.findMany.mockResolvedValue([{ ...rate, service: "OUTSTATION_ROUND_TRIP", status: "APPROVED", fare: new Prisma.Decimal(4700), terms: { ...terms, includedKm: "300", minimumKmPerDay: "300", perKm: "14", operational: { service: "ROUNDTRIP", vehicleId: "vehicle", driverId: "driver", waitingFreeMinutes: "0" } } }]);
    const result = await quoteService.quote({ ...request, service: "OUTSTATION_ROUND_TRIP", days: "2", distanceKm: "650" });
    expect(result.snapshot).toMatchObject({ vendorFare: "10100.00", distanceCharge: "700.00", platformFee: "50.00", finalPayable: "10150.00" });
    expect(db.pricingQuote.create).toHaveBeenCalledOnce();
  });
  it("rejects a simplified price when its aligned driver is no longer eligible", async () => {
    db.pricingRateVersion.findMany.mockResolvedValue([{ ...rate, status: "APPROVED", terms: { ...terms, operational: { service: "ONE_WAY", vehicleId: "vehicle", driverId: "driver" } } }]);
    db.vehicle.findFirst.mockResolvedValueOnce({ id: "vehicle", category: "SEDAN", vendorId: "vendor" }).mockResolvedValueOnce(null);
    await expect(quoteService.quote(request)).rejects.toThrow("active aligned");
    expect(db.pricingQuote.create).not.toHaveBeenCalled();
  });
  it("uses a market fallback only for an explicit vendor allowlist",async()=>{db.pricingRateVersion.findMany.mockResolvedValue([]);db.pricingRateVersion.findUnique.mockResolvedValue({...rate,vendorId:"market-source",status:"APPROVED"});db.pricingPolicy.findMany.mockResolvedValue([...quotePolicies(),{...band,id:"master",kind:"MASTER",data:{...terms,fallbackRateVersionId:"r",fallbackVendorIds:["vendor"]}}]);const q=await quoteService.quote(request);expect(q.snapshot.policies).toContainEqual({id:"master",kind:"MASTER",version:1});expect(q.snapshot.vendorId).toBe("vendor");});
  it("does not silently fall back for an unapproved vendor",async()=>{db.pricingRateVersion.findMany.mockResolvedValue([]);db.pricingPolicy.findMany.mockResolvedValue([...quotePolicies(),{...band,id:"master",kind:"MASTER",data:{...terms,fallbackRateVersionId:"r",fallbackVendorIds:["other"]}}]);await expect(quoteService.quote(request)).rejects.toThrow("PRICE_UNAVAILABLE");});
  it("does not change a historical snapshot when rate terms change",async()=>{const q=await quoteService.quote(request),saved=JSON.stringify(q.snapshot);db.pricingRateVersion.findMany.mockResolvedValue([{...rate,status:"APPROVED",version:3,fare:new Prisma.Decimal(2000)}]);await quoteService.quote({...request,idempotencyKey:"other"});expect(JSON.stringify(q.snapshot)).toBe(saved);});
  it("keeps refund/cancellation evidence intact and prevents quote reuse",async()=>{db.pricingQuote.findUnique.mockResolvedValue({id:"quote",ownerId:"customer",vehicleId:"vehicle",expiresAt:new Date("2031-01-01"),booking:{id:"cancelled-booking"},snapshot:{finalPayable:"1050.00"}});await expect(consumeQuote(db as never,"quote","customer","vehicle")).rejects.toThrow("QUOTE_ALREADY_USED");expect(db.pricingQuote.create).not.toHaveBeenCalled();});
  it("never treats a simulation as a reservable quote",async()=>{const q=await quoteService.quote(request,false);expect(q.id).toBeNull();expect(db.pricingQuote.create).not.toHaveBeenCalled();});
  it("checks reserved discount budgets",async()=>{db.pricingPolicy.findMany.mockResolvedValue([...quotePolicies(),{...band,id:"discount",kind:"DISCOUNT",data:{name:"limited",fixed:"20",percent:"0",cap:"20",vendorPercent:"0",budget:"10"}}]);await expect(quoteService.quote(request)).rejects.toThrow("budget");expect(db.pricingQuote.create).not.toHaveBeenCalled();});
  it("applies approved Smart Return fare only after existing eligibility passes",async()=>{db.pricingRateVersion.findMany.mockResolvedValue([{...rate,status:"APPROVED",smartReturnFare:new Prisma.Decimal(700)}]);db.smartReturnListing.findUnique.mockResolvedValue({id:"sr",status:"PUBLISHED",expiresAt:new Date("2030-01-03"),vendorId:"vendor",vehicleId:"vehicle",pickupLocation:"Mumbai",dropLocation:"Pune",tripId:"trip",bookingId:"booking",trip:{tripCompletedAt:new Date("2029-12-31")},booking:{bookingNumber:"RG-test",pickupLocation:"Pune",dropLocation:"Mumbai",tripType:"ONEWAY"}});const q=await quoteService.quote({...request,origin:"Mumbai",destination:"Pune",smartReturnListingId:"sr"});expect(q.snapshot.vendorFare).toBe("700.00");expect(q.snapshot.normalFare).toBe("1000.00");expect(q.snapshot.smartReturn).toMatchObject({eligibility:{eligible:true}});});
});
